[13.0][stock_request_stage][add] new module to manage stock requests using stages
OCA/stock-logistics-warehouse pull request #1200
Opened 2021-07-15 16:46 UTC by JordiBForgeFlow

This module allows you to manage the completion of stock requests in stages.
A Kanban view is added to stock requests, allowing you to move stock requests
across the defined stages.

![image](https://user-images.githubusercontent.com/7683926/125826197-65d76e5e-d89f-4aad-bcb1-5991bf2b4310.png)

2021-07-15 16:47 UTC, JordiBForgeFlow commented
@ForgeFlow @HviorForgeFlow

2021-07-16 06:00 UTC, JordiMForgeFlow commented on stock_request_stage/__manifest__.py
> +# Copyright 2018 Creu Blanca
```suggestion
# Copyright 2021 ForgeFlow, S.L.
```

2021-07-16 06:00 UTC, JordiMForgeFlow commented
When trying to set a cover image in the kanban card:

![image](https://user-images.githubusercontent.com/71635103/125899690-302c6102-8a9a-4e42-81bd-e3dab189b047.png)

2021-07-16 06:02 UTC, JordiMForgeFlow commented
The button "Share" of the kanban is missing some method:

![image](https://user-images.githubusercontent.com/71635103/125899791-a84612e9-e229-4c17-8fbe-297b43facbf2.png)

2021-07-16 06:36 UTC, AaronHForgeFlow commented
Would it be possible to integrate this module with the base_kanban_stage module in server tools?

2021-07-16 13:59 UTC, JordiBForgeFlow commented
@AaronHForgeFlow interesting idea! In this case, though, I am in need of some specific features like adding images or updating the states of the stock request. Also, it's been done already...

![image](https://user-images.githubusercontent.com/7683926/125959535-c21817e8-1daf-457a-bfed-45888f5ce367.png)

2022-09-06 15:20 UTC, rousseldenis commented
@JordiBForgeFlow Could you rebase ?

2022-10-18 15:35 UTC, rousseldenis commented
@JordiBForgeFlow

2022-10-19 07:30 UTC, rousseldenis requested changes
Apart changes, @JordiBForgeFlow isn't this introducing complexity ?

Having two fields to represent a 'stage' is quite confusing for users.

However, could you be aware of 16 migrations as this can be merged in stock_request IMHO

2022-10-19 07:30 UTC, rousseldenis commented on stock_request_stage/models/stock_request.py
> +        default=_get_default_stage_id,
You can use lambda and put method under.

2022-10-19 07:30 UTC, rousseldenis commented on stock_request_stage/models/stock_request.py
> +                    picking.action_confirm()
Isn't it possible to use multi recordset for both actions ?

2022-10-19 07:30 UTC, rousseldenis commented on stock_request_stage/models/stock_request_stage.py
> +    def _get_default_project_ids(self):
Is this used somewhere ?

2023-03-26 12:26 UTC, closed without merging