[14.0][FIX] stock_request: action_view_stock_requests
OCA/stock-logistics-warehouse pull request #1275
Opened 2021-10-07 20:22 UTC by Kosaaaaa

FIX action_view_stock_requests for non admin.

Users without admin rules could not open this action.

2021-10-15 08:55 UTC, sebalix approved these changes
LG

2021-10-15 10:01 UTC, etobella commented on stock_request/__manifest__.py
> +    "version": "14.0.1.0.5",
No need to change the version. Will be done by runbot

2021-10-18 11:57 UTC, rousseldenis requested changes

2021-10-18 11:57 UTC, rousseldenis commented on stock_request/models/stock_request_order.py
> +        action = self.env.ref("stock_request.action_stock_request_form").sudo().read()[0]
```suggestion
        action = self.env["ir.actions.act_window"]._for_xml_id("stock_request.action_stock_request_form")
```

2021-10-18 11:57 UTC, rousseldenis commented on stock_request/__manifest__.py
> +    "version": "14.0.1.0.5",
You don't need to update this unless you have no migrations script in your PR. OCA git bot will update it automatically.

2021-11-24 07:39 UTC, rousseldenis commented
@Kosaaaaa Do you plan to fix this ?

2021-11-24 08:03 UTC, Kosaaaaa commented
> @Kosaaaaa Do you plan to fix this ?

Fixed

2021-11-24 08:28 UTC, rousseldenis commented
@Kosaaaaa Could you squash your commits as soon as tests are done ?

2021-11-24 08:29 UTC, Kosaaaaa commented
> @Kosaaaaa Could you squash your commits as soon as tests are done ?

No problem

2021-11-24 08:32 UTC, Kosaaaaa commented
> @Kosaaaaa Could you squash your commits as soon as tests are done ?

done

2021-12-14 15:35 UTC, rousseldenis commented
Seems that this one passed before. Sorry
https://github.com/OCA/stock-logistics-warehouse/pull/1326

2021-12-14 15:35 UTC, closed without merging