[14.0][MIG] Account_move_line_stock_info
OCA/stock-logistics-warehouse pull request #1277
Opened 2021-10-15 11:22 UTC by JoanMForgeFlow

Standard migration to v.14
@mariadforgeflow
@bernatpforgeflow

2021-10-15 11:34 UTC, mariadforgeflow approved these changes
LGTM!

2021-10-18 11:45 UTC, rousseldenis approved these changes
code review

2021-10-18 11:47 UTC, rousseldenis requested changes

2021-10-18 11:47 UTC, rousseldenis commented on account_move_line_stock_info/tests/test_account_move_line_stock_move.py
> +        picking_in.action_done()
```suggestion
        picking_in._action_done()
```

2021-10-18 11:47 UTC, rousseldenis commented on account_move_line_stock_info/tests/test_account_move_line_stock_move.py
> +        picking_out.action_done()
```suggestion
        picking_out._action_done()
```

2021-10-18 11:47 UTC, rousseldenis commented on account_move_line_stock_info/tests/test_account_move_line_stock_move.py
> +        picking_out.action_done()
Missed that

2021-10-18 11:58 UTC, AaronHForgeFlow approved these changes
:+1: Functional review. Pending to fix CI

2021-10-18 14:54 UTC, AaronHForgeFlow commented
@rousseldenis it seems CI is ok now :)

2021-10-19 06:26 UTC, JoanMForgeFlow commented
@rousseldenis can you update your review please?

2021-10-19 08:52 UTC, rousseldenis approved these changes

2021-10-19 09:02 UTC, LoisRForgeFlow commented
/ocabot merge nobump

2021-10-19 09:45 UTC, merged