[15.0][MIG] stock_request
OCA/stock-logistics-warehouse pull request #1343
Opened 2021-12-31 13:14 UTC by BernatPForgeFlow

2022-01-04 07:11 UTC, JoanMForgeFlow approved these changes
LGTM!

2022-01-04 11:36 UTC, LoisRForgeFlow commented
/ocabot migration stock_request

2022-01-18 16:24 UTC, ajaniszewska-dev approved these changes

2022-02-01 11:57 UTC, BernatPForgeFlow commented
@LoisRForgeFlow @JordiBForgeFlow @sebalix @pedrobaeza

2022-02-06 11:41 UTC, sebalix commented
/ocabot migration stock_request

2022-02-06 11:51 UTC, sebalix requested changes
Could you squash the following type of commits to reduce the size of the history?

- `[UPD] Update stock_request.pot` from `oca-travis`
- `Update translation files` from `oca-transbot`
- `[UPD] README.rst` from `OCA-git-bot`

2022-02-06 11:51 UTC, sebalix commented on stock_request/models/stock_request_order.py
>          action = self.env.ref("stock_request.stock_request_order_action").read()[0]
```python
        action = self.env["ir.actions.act_window"]._for_xml_id("stock_request.stock_request_order_action")
```
This fix should have been applied also on 14.0 version.

2022-02-07 10:53 UTC, BernatPForgeFlow commented on stock_request/models/stock_request_order.py
>          action = self.env.ref("stock_request.stock_request_order_action").read()[0]
@sebalix  Okay, I'll squash them now. Do I backport the changes to v14?

2022-02-07 11:01 UTC, JoanMForgeFlow approved these changes
Code seems OK!

2022-02-11 15:38 UTC, MiquelRForgeFlow approved these changes

2022-02-11 15:40 UTC, MiquelRForgeFlow commented
But IMO, https://github.com/OCA/stock-logistics-warehouse/pull/1350 looks better.

2022-02-11 17:27 UTC, JordiBForgeFlow commented
@BernatPForgeFlow can you fetch from https://github.com/OCA/stock-logistics-warehouse/pull/1350 the parts that might be interesting to fetch? @olveracuenca we can then merge this PR.

2022-02-16 08:21 UTC, BernatPForgeFlow commented
> @BernatPForgeFlow can you fetch from #1350 the parts that might be interesting to fetch? @olveracuenca we can then merge this PR.

Okay, already fetched some parts.

2022-02-18 09:12 UTC, LoisRForgeFlow commented
/ocabot merge nobump

2022-02-18 09:19 UTC, merged