[13.0][FIX] stock_move_location: Method returns mixed types of values
OCA/stock-logistics-warehouse pull request #1390
Opened 2022-03-10 16:35 UTC by carlosdauden

Fix refactor:
https://github.com/OCA/stock-logistics-warehouse/commit/b7915c1472e113dec28befd280a2857b7f5fe399#diff-6b49508b3044fb565412e49f2580cdf202a7d6bd2a3e59431d95336d484ec10cL117-R142
https://github.com/OCA/stock-logistics-warehouse/pull/829

@Tecnativa TT35019

2022-03-10 16:36 UTC, carlosdauden commented
@JordiBForgeFlow @LoisRForgeFlow can you review?

2022-03-10 16:40 UTC, sergio-teruel approved these changes

2022-03-10 16:56 UTC, pedrobaeza approved these changes

2022-03-10 17:17 UTC, rousseldenis requested changes
I see that changed lines are not covered by tests.

@carlosdauden Could you do it in order to avoid a further regression ? Thanks

2022-03-31 09:47 UTC, carlosdauden commented
Already included here: https://github.com/OCA/stock-logistics-warehouse/pull/1095

2022-03-31 09:47 UTC, closed without merging