[FIX] Update immediately_usable_qty_today field triggers
OCA/stock-logistics-warehouse pull request #1458
Opened 2022-07-26 10:37 UTC by cesar-tecnativa

Add missing triggers of computational field immediately_usable_qty_today

 TT38197

2022-07-26 16:21 UTC, pedrobaeza requested changes
And please follow commit message guidelines including module name.

2022-07-26 16:21 UTC, pedrobaeza commented on sale_stock_available_info_popup/models/sale_order.py
> +        compute="_compute_immediately_usable_qty_today", store=True
This can't be stored, as it depends on context.

2022-07-28 07:24 UTC, pedrobaeza commented on sale_stock_available_info_popup/models/sale_order.py
> +        "product_id.immediately_usable_qty",
This shouldn't be added, as only direct things that you change in your screen will provoke the recomputation, and you can't change this data through it.

2022-07-28 07:24 UTC, pedrobaeza commented on sale_stock_available_info_popup/models/sale_order.py
> +        "order_id.state",
Why adding this one?

2022-07-28 07:24 UTC, pedrobaeza commented on sale_stock_available_info_popup/models/sale_order.py
> +        "display_qty_widget",
And this one?

2022-07-28 07:24 UTC, pedrobaeza commented on sale_stock_available_info_popup/models/sale_order.py
> +        self.immediately_usable_qty_today = 0
Is there any difference?

2022-07-28 07:24 UTC, pedrobaeza commented on sale_stock_available_info_popup/tests/test_sale_stock_available_info_popup.py
> +    @users("admin", "stock_user")
Why this change?

2022-08-31 12:11 UTC, chienandalu commented
Changes applied

2022-08-31 12:12 UTC, chienandalu approved these changes

2022-08-31 12:14 UTC, pedrobaeza approved these changes

2022-08-31 12:15 UTC, pedrobaeza commented
/ocabot merge patch

2022-08-31 12:26 UTC, merged

2022-08-31 12:27 UTC, pedrobaeza commented
Is this needed in v14?

2022-08-31 12:35 UTC, chienandalu commented
Well, the module isn't migrated so... :sweat_smile: