[MIG] stock_reserve 15.0
OCA/stock-logistics-warehouse pull request #1485
Opened 2022-09-15 10:24 UTC by flachica

2022-09-28 13:54 UTC, victoralmau commented
Thank you for your work.
There is something wrong with this migration, the `stock_reserve_sale` addon is added and it should not.

Maybe it would be a good idea to finish the migration to v14 (https://github.com/OCA/stock-logistics-warehouse/pull/1346) and then continue with this one.

2022-09-28 14:05 UTC, flachica commented
Sorry @victoralmau, this module is migrated in #1486. I got confused with branch

2022-10-07 07:52 UTC, rousseldenis commented
/ocabot migration stock_reserve

2022-10-07 07:53 UTC, rousseldenis commented
@flachica Could you remove unrelated files (stock_reserve_sale) ?

2022-10-07 08:26 UTC, flachica commented
> @flachica Could you remove unrelated files (stock_reserve_sale) ?

@rousseldenis In this PR I got confused about the branch but I thought I had solved it. Please, can you tell me where you see the remaining files? I can not find it

2022-10-07 08:47 UTC, rousseldenis commented
> > @flachica Could you remove unrelated files (stock_reserve_sale) ?
> 
> @rousseldenis In this PR I got confused about the branch but I thought I had solved it. Please, can you tell me where you see the remaining files? I can not find it

No, it's ok, wrong browser tab :sweat:

2022-10-24 15:16 UTC, victoralmau requested changes

2022-10-24 15:16 UTC, victoralmau commented on stock_reserve/model/stock_reserve.py
> +        action_dict = action.read()[0]
```suggestion
        action_dict = self.env["ir.actions.act_window"]._for_xml_id(
            "stock.stock_move_action"
        )
```

2022-10-24 15:16 UTC, victoralmau commented on stock_reserve/model/product.py
> +        action_dict = self.env.ref(ref).read()[0]
```suggestion
       action_dict = self.env["ir.actions.act_window"]._for_xml_id(
            "stock_reserve.action_stock_reservation_tree"
        )
        product_ids = self.mapped("product_variant_ids.id")
```

2022-10-24 15:16 UTC, victoralmau commented on stock_reserve/model/product.py
> +        action_dict = self.env.ref(ref).read()[0]
```suggestion
        action_dict = self.env["ir.actions.act_window"]._for_xml_id(
            "stock_reserve.action_stock_reservation_tree"
        )
```

2022-10-24 15:16 UTC, victoralmau commented on stock_reserve/tests/test_stock_reserve.py
> +    def test_reservation_and_reservation_release(self):
```suggestion
    def _create_stock_reservation(self, qty):
        form_reservation = Form(self.env["stock.reservation"])
        form_reservation.product_id = self.product
        form_reservation.product_uom_qty = qty
        form_reservation.location_id = self.warehouse.lot_stock_id
        return form_reservation.save()
    def test_reservation_and_reservation_release(self):
```

2022-10-24 15:16 UTC, victoralmau commented on stock_reserve/tests/test_stock_reserve.py
> +        reservation_1 = form_reservation_1.save()
```suggestion
        reservation_1 = self._create_stock_reservation(6)
```

2022-10-24 15:16 UTC, victoralmau commented on stock_reserve/tests/test_stock_reserve.py
> +        reservation_2 = form_reservation_2.save()
```suggestion
        reservation_2 = self._create_stock_reservation(1)
```

2022-10-24 15:16 UTC, victoralmau commented on stock_reserve/tests/test_stock_reserve.py
> +        reservation_1 = form_reservation_1.save()
```suggestion
        reservation_1 = self._create_stock_reservation(11)
```

2022-10-24 15:16 UTC, victoralmau commented on stock_reserve/tests/test_stock_reserve.py
> +        reservation_1 = form_reservation_1.save()
```suggestion
        reservation_1 = self._create_stock_reservation(6)
        reservation_1.date_validity = = fields.Date.from_string("2021-01-01")
```

2022-10-27 06:30 UTC, flachica commented
@victoralmau How I can set this commit as coauthored with you? You are made a lot of valueable suggestions

2022-10-27 06:52 UTC, rousseldenis commented
> @victoralmau How I can set this commit as coauthored with you? You are made a lot of valueable suggestions

You can use git cherry-pick to do so.

2022-10-27 06:56 UTC, victoralmau approved these changes
Code review OK.

IMO, you don't need to add me as a co-author.

2022-11-29 13:41 UTC, CasVissers-360ERP commented
@rousseldenis Think this one should be ready to merge?

2022-11-29 14:15 UTC, rousseldenis approved these changes
Code review

2022-11-29 14:15 UTC, rousseldenis commented
/ocabot merge patch

2022-11-29 14:26 UTC, merged