[14.0][MIG] stock_request_mrp: Migration to 14.0
OCA/stock-logistics-warehouse pull request #1499
Opened 2022-10-08 23:26 UTC by pedrobaeza

@Tecnativa TT39761

2022-10-08 23:26 UTC, pedrobaeza commented
/ocabot migration stock_request_mrp

2022-10-08 23:34 UTC, pedrobaeza commented
The tests error seems not related to this module.

2022-10-11 08:13 UTC, rousseldenis commented
> The tests error seems not related to this module.

It seems so:

![image](https://user-images.githubusercontent.com/19529533/195035622-d9e2ef2f-edd3-4de7-9eac-ef9e6ae20158.png)

@pedrobaeza Could you check ?

2022-10-11 08:25 UTC, rousseldenis requested changes

2022-10-11 08:25 UTC, rousseldenis commented on stock_request_mrp/models/mrp_production.py
> +        action = self.env.ref("stock_request.action_stock_request_form").read()[0]
Please use _for_xml_id()

2022-10-11 08:25 UTC, rousseldenis commented on stock_request_mrp/models/stock_request.py
> +        action = self.env.ref("mrp.mrp_production_action").read()[0]
same as above

2022-10-11 08:25 UTC, rousseldenis commented on stock_request_mrp/models/stock_request_order.py
> +        action = self.env.ref("mrp.mrp_production_action").read()[0]
Same here

2022-10-11 08:25 UTC, rousseldenis commented on stock_request_mrp/tests/test_stock_request_mrp.py
> +    def setUp(self):
You maybe want to use setUpClass instead

2023-01-05 14:03 UTC, victoralmau approved these changes

2023-01-05 15:07 UTC, pedrobaeza commented
@rousseldenis can you please check again?

2023-01-13 16:55 UTC, pedrobaeza commented
@rousseldenis please update your review

2023-01-16 08:11 UTC, rousseldenis approved these changes
LGTM

2023-01-16 08:12 UTC, pedrobaeza commented
/ocabot merge nobump

2023-01-16 08:48 UTC, merged