[15.0][MIG] stock_lot_filter_available: Migration to version 15.0
OCA/stock-logistics-warehouse pull request #1523
Opened 2022-10-27 10:57 UTC by CarlosRoca13

cc @Tecnativa TT36554

please @carlosdauden @victoralmau review this

2022-10-27 11:14 UTC, victoralmau requested changes

2022-10-27 11:14 UTC, victoralmau commented on stock_lot_filter_available/tests/test_stock_lot_filter_available.py
> +            {"name": "Test product", "type": "product", "tracking": "lot"}
```suggestion
            {"name": "Test product", "detailed_type": "product", "tracking": "lot"}
```

2022-10-27 11:20 UTC, CarlosRoca13 commented
@victoralmau Changed!

2022-10-27 11:21 UTC, victoralmau approved these changes
Code and functionality OK

2022-11-08 10:39 UTC, sergio-teruel approved these changes

2022-11-08 10:43 UTC, pedrobaeza commented
/ocabot migration stock_lot_filter_available
/ocabot merge nobump

2022-11-08 11:00 UTC, pedrobaeza commented
/ocabot merge nobump

2022-11-09 07:12 UTC, pedrobaeza commented
/ocabot merge nobump

2022-11-09 07:28 UTC, merged