FIX: bad bom are used in potential qty
OCA/stock-logistics-warehouse pull request #1559
Opened 2022-11-20 19:47 UTC by flotho

When working with different BOMs for multiple variant , the field bom_ids is referencing all the bom associated to the product template. The variant_bom_ids field is no more relevant as it's incomplete. It's not considering that bom without variant could apply on a variant.
So all the references to bom_ids in this mocule could refrence bad Bom depending of the setup.
This PR try to correct this behaviour by introducing a field referencing appropriate boms only regarding the variant and the absence of variant.

2022-11-20 20:01 UTC, flotho commented
Hi @OCA/logistics-maintainers, any review would be welcome

2023-01-18 14:04 UTC, flotho commented
hi @sbidoul sorry for the request.
I have a test failure with docker. Any chance to help me on this ?

Regards

2023-01-18 14:06 UTC, sbidoul commented
This looks like a transient issue.

2023-01-18 15:39 UTC, flotho commented
> This looks like a transient issue.

Not sure to understand if I can help on this, let me know

2023-01-18 19:18 UTC, sbidoul commented
@flotho I meant it looks like a transient error in the GitHub infrastructure. Just push something to restart the tests.

2023-01-18 21:34 UTC, flotho commented
thanks thanks thanks @sbidoul

2023-01-19 07:56 UTC, rousseldenis commented
@flotho Could you fix pre-commit ?

2023-01-19 07:59 UTC, rousseldenis requested changes
Seems good. Some comments

2023-01-19 07:59 UTC, rousseldenis commented on stock_available_mrp/models/product_product.py
> +    appropriate_bom_ids = fields.One2many(
Could you put fields on top ?

2023-01-19 07:59 UTC, rousseldenis commented on stock_available_mrp/models/product_product.py
> +        "virtual_available",
You should add your new field here

2023-01-19 07:59 UTC, rousseldenis commented on stock_available_mrp/models/product_product.py
> +            template_bom_ids = prod.bom_ids.filtered(lambda b: b.product_id.id is False)
```suggestion
            template_bom_ids = prod.bom_ids.filtered(lambda b: not b.product_id)
```

2023-01-19 16:28 UTC, rousseldenis commented
@flotho Could you fix pre-commit and squash your commit (I suggest you install pre-commit locally as it will correct your code before committing)?

2023-07-02 12:29 UTC, closed without merging

2024-02-14 10:23 UTC, flotho commented
looks like problem has been solved there https://github.com/OCA/stock-logistics-warehouse/commit/ff81ff233474f8c8ad654834e7a7ca0f68cba50f