[15.0][MIG]stock_inventory_exclude_sublocation
OCA/stock-logistics-warehouse pull request #1574
Opened 2022-12-08 09:22 UTC by Chanakya-OSI

2022-12-08 09:25 UTC, rousseldenis commented
/ocabot migration stock_inventory_exclude_sublocation

Same remarks as in https://github.com/OCA/stock-logistics-warehouse/pull/1573

2024-01-17 13:09 UTC, mileo commented
Can some one reopen this pull request?

2024-04-17 11:51 UTC, LoisRForgeFlow requested changes
The migration does not look correct, you are changing all tests to expect what you are getting instead of fixing the code to do what was expected by the module

2024-04-17 11:51 UTC, LoisRForgeFlow commented on stock_inventory_exclude_sublocation/tests/test_exclude_sublocation.py
> +            starting_inv.action_state_to_done()
Here

2024-04-17 11:51 UTC, LoisRForgeFlow commented on stock_inventory_exclude_sublocation/tests/test_exclude_sublocation.py
> +            self.assertEqual(len(lines), 2, "Not all expected products are " "included")
Here

2024-04-17 11:51 UTC, LoisRForgeFlow commented on stock_inventory_exclude_sublocation/tests/test_exclude_sublocation.py
> +                1,
Here

2024-04-23 12:08 UTC, LoisRForgeFlow commented
The functionality of this module has been included in the base module after this PR https://github.com/OCA/stock-logistics-warehouse/pull/1991. So we can close this one now.

2024-04-23 12:08 UTC, closed without merging