[16.0][MIG] stock_cycle_count
OCA/stock-logistics-warehouse pull request #1669
Opened 2023-03-23 05:19 UTC by Urvisha-OSI

2023-04-17 13:19 UTC, rousseldenis commented
/ocabot migration stock_cycle_count

2023-04-17 13:20 UTC, rousseldenis commented
@Urvisha-OSI To allow reviewers being able to test this, could you include your dependencies following: https://github.com/OCA/maintainer-tools/wiki/Use-temporary-reference%28s%29-to-another-pull-request%28s%29 ?

Thanks

2023-07-12 16:08 UTC, serCliff commented
Hello @rousseldenis could you make a rebase and fix the test?

After that I could try the module with the runbot.


Thank you

2023-11-24 11:13 UTC, ArnauCForgeFlow requested changes

2023-11-24 11:13 UTC, ArnauCForgeFlow commented on stock_cycle_count/models/stock_inventory.py
> +                inv.stock_quant_ids.mapped(lambda x: abs(x.discrepancy_qty))
```suggestion
                inv.stock_quant_ids.mapped(lambda x: abs(x.inventory_diff_quantity))
```
"discrepancy_qty" it seems that is no longer available in version 16, i suggest change this attribute for "inventory_diff_quantity"

2023-12-21 08:48 UTC, rousseldenis commented
@Urvisha-OSI Could you update this ?

2024-05-22 14:20 UTC, LoisRForgeFlow commented
Closed due to inactivity in favor of https://github.com/OCA/stock-logistics-warehouse/pull/2045

2024-05-22 14:20 UTC, closed without merging