[ADD] new module stock_quant_import
OCA/stock-logistics-warehouse pull request #1754
Opened 2023-06-14 06:14 UTC by PicchiSeba

This PR aims to add a new module making it easier to import stock data

2024-01-16 12:26 UTC, rousseldenis requested changes
LGTM. Apart a better module usage description

2024-01-16 12:26 UTC, rousseldenis commented on stock_quant_import/readme/DESCRIPTION.rst
> +Load a csv containing the new data of stock information.
@PicchiSeba Could you describe in a USAGE file, what content (what should the file look like - columns etc...) ?

2024-01-19 16:48 UTC, PicchiSeba commented
I'm trying to figure out why tests are OK on my machine but they're failing on OCA's

2024-01-22 11:15 UTC, PicchiSeba commented
@rousseldenis 

It seems  that `stock_inventory_discrepancy` and `stock_quant_import` conflict with each other.

The module `stock_inventory_discrepancy` adds an additional modal to confirm `stock.quant` changes.

I added a way to detect that module in the tests and to properly manage it.

2024-02-02 14:44 UTC, PicchiSeba commented
With the last force-pushed commit I added the maintainers

2024-02-02 14:44 UTC, HekkiMelody approved these changes
Code review, LGTM. We have also been using this successfully in production for a couple of months now.

2024-02-02 14:44 UTC, HekkiMelody commented on stock_quant_import/tests/test_stock_import.py
> +            cls.ConfirmDiscrepancyWiz = cls.env["confirm.discrepancy.wiz"]
comment(non-blocking): I think an easier way to avoid the issue would have been to add a context variable

https://github.com/OCA/stock-logistics-warehouse/blob/16.0/stock_inventory_discrepancy/models/stock_quant.py#L55-L57

More importantly: does the module work from the UI even with `stock_inventory_discrepancy` installed?

2024-02-02 15:36 UTC, PicchiSeba commented on stock_quant_import/tests/test_stock_import.py
> +            cls.ConfirmDiscrepancyWiz = cls.env["confirm.discrepancy.wiz"]
1. That was my first attempt actually, but setting that flag to True didn't seem to work (in the tests at least)

2. It still works with the other module. The only difference is an additional step required to apply stock amounts

2024-07-07 12:27 UTC, closed without merging