[MIG][16.0] stock_reserve_rule
OCA/stock-logistics-warehouse pull request #1794
Opened 2023-07-14 07:47 UTC by rousseldenis

2023-07-14 07:48 UTC, rousseldenis commented
/ocabot migration stock_reserve_rule

2023-07-17 15:10 UTC, jbaudoux requested changes
The v14 package type is replaced by package level in v16

2023-07-17 15:10 UTC, jbaudoux commented on stock_reserve_rule/__manifest__.py
> +    ],
```suggestion
        "product_packaging_level"
    ],
```

2023-07-17 15:10 UTC, jbaudoux commented on stock_reserve_rule/models/stock_reserve_rule.py
> +        help="Optional packaging when using 'Full Packaging'.\n"
```suggestion
    packaging_level_ids = fields.Many2many(
        comodel_name="product.packaging.level",
        help="Optional packaging level when using 'Full Packaging'.\n"
```

2023-07-17 15:10 UTC, jbaudoux commented on stock_reserve_rule/models/stock_reserve_rule.py
> +        packaging_type_filter = self.packaging_type_ids
```suggestion
        packaging_type_filter = self.packaging_level_ids
```

2023-07-17 15:10 UTC, jbaudoux commented on stock_reserve_rule/models/stock_reserve_rule.py
> +                        packaging.package_type_id in packaging_type_filter
```suggestion
                        packaging.packaging_level_id in packaging_type_filter
```

2023-07-17 15:10 UTC, jbaudoux commented on stock_reserve_rule/views/stock_reserve_rule_views.xml
> +                                        name="packaging_type_ids"
```suggestion
                                        name="packaging_level_ids"
```

2023-07-18 11:29 UTC, jbaudoux approved these changes

2023-08-29 17:07 UTC, hparfr approved these changes
Functionnal review, LGTM thanks

2023-11-06 13:31 UTC, hparfr commented
@rousseldenis can you please remove the last commit `[[DONT MERGE] test-requirements.txt]`

2024-03-05 09:29 UTC, AungKoKoLin1997 approved these changes
LGTM.

2024-03-11 14:33 UTC, lmignon commented on stock_reserve_rule/models/stock_move.py
> +                        if need_zero:
@rousseldenis 
```python
if  float_is_zero(still_need, precision_rounding=rounding):
```

2024-03-14 18:15 UTC, dreispt commented
@rousseldenis Does this have a dependency waiting to be merged?

2024-03-15 14:01 UTC, jbaudoux commented
@rousseldenis The dependency has been merged. Can you drop the related commit so that we can merge this one?

2024-10-07 08:50 UTC, jbaudoux commented
> @rousseldenis The dependency has been merged. Can you drop the related commit so that we can merge this one?

@rousseldenis The dependency has been merged. Can you drop the related commit so that we can merge this one?

2024-10-07 08:58 UTC, jbaudoux commented
/ocabot merge nobump

2024-10-07 09:06 UTC, merged