stock_reserve: port to 9.0
OCA/stock-logistics-warehouse pull request #189
Opened 2016-09-13 13:29 UTC by katyukha

*stock_reserve* only modifications from PRs #186 #187 #188

2016-09-14 22:07 UTC, lasley commented on README.md
> +[stock_reserve](stock_reserve/) | 9.0.0.2.0 | Stock reservations on products
This file is maintained automatically & editing it as such will cause conflicts with our automation. Please reverse change

2016-09-14 22:08 UTC, lasley commented on stock_reserve/__openerp__.py
> + 'version': '9.0.0.2.0',
9.0.1.0.0

2016-09-14 22:11 UTC, lasley commented on stock_reserve/model/stock_reserve.py
> +        """ Confirm a reservations
s/Confirm a reservations/Confirm reservations

2016-09-14 22:12 UTC, lasley commented on stock_reserve/model/stock_reserve.py
> +        self.mapped('move_id').action_confirm()
Why mapped on m2o?

2016-09-14 22:12 UTC, lasley commented on stock_reserve/model/stock_reserve.py
> +        self.mapped('move_id.picking_id').action_assign()
Why mapped on m2o?

2016-09-14 22:16 UTC, lasley requested changes
Thanks for the submission @katyukha - comments inline

2016-09-14 22:40 UTC, pedrobaeza commented on stock_reserve/model/stock_reserve.py
> +        self.mapped('move_id').action_confirm()
`self` can contain more than one record, so mapped is needed

2016-09-15 06:08 UTC, katyukha commented
Fixes sent) Thanks for review)

2016-09-15 19:46 UTC, lasley approved these changes

2016-11-11 17:47 UTC, gs-clearcorp commented
:+1:

2016-11-11 18:01 UTC, merged