[14.0][IMP] stock_vertical_lift: filter notifications by screen
OCA/stock-logistics-warehouse pull request #1944
Opened 2024-02-16 13:13 UTC by SilvioC2C

If the same user opens multiple shuttles operation on different screens, notifications for a specific shuttle will be displayed on all of them, regardless of the shuttle operation that triggered the notification.

This commit allows filtering notifications for screen, so that only screens displaying shuttle operations related to the current notifications will display them.

Notifications that are not shuttle-related are not filtered out.

Depends on https://github.com/OCA/web/pull/2749

2024-02-16 14:44 UTC, simahawk requested changes
LG overall!

2024-02-16 14:44 UTC, simahawk commented on stock_vertical_lift/static/src/js/web_client.js
> +         * Override method to split notifications
```suggestion
         * Override method to filter out shuttle notifications that are not for the current device.
```

2024-02-16 14:44 UTC, simahawk commented on stock_vertical_lift/static/src/js/web_client.js
> +        },
```suggestion
            if (shuttle_notifications.length > 0) {
                const filtered_shuttle_notifications = this.filter_shuttle_notifications(
                    shuttle_notifications
                );
                // Notifications will be displayed if:
                // 1) they're not shuttle-related
                // 2) they're included in the filtered shuttle notifications
                // NB: using ``filter`` allows keeping notifications' order
                notifications = notifications.filter(
                        (n) =>
                            !this.is_shuttle_notification(n) ||
                            filtered_shuttle_notifications.indexOf(n) !== -1
                    )
                );
            }
            this._super(notifications);
        },
```

2024-02-16 14:44 UTC, simahawk commented on stock_vertical_lift/models/vertical_lift_shuttle.py
> +        self.ensure_one()
calling ensure_one such private methods (private to this feature) is pointless.

2024-02-16 14:44 UTC, simahawk commented on stock_vertical_lift/models/vertical_lift_shuttle.py
> +        for model in self._model_for_mode.values():
a comment would be nice

2024-02-19 12:59 UTC, simahawk approved these changes

2024-02-19 12:59 UTC, simahawk commented
the other PR is getting merged

2024-03-26 09:46 UTC, SilvioC2C commented
@simahawk shall we merge?

2024-03-26 14:16 UTC, simahawk commented
/ocabot merge minor

2024-03-26 14:25 UTC, merged