[IMP] stock_move_packaging_qty: report done packaging qtys
OCA/stock-logistics-warehouse pull request #1988
Opened 2024-04-09 12:45 UTC by yajo

The title sounds like a simple task, but it requires many changes:

- Store done pkg qtys in `stock.move.line` records.
- The qtys are not computed. Instead, the user must write them by hand. This happens because many times the packaging just indicates an approximate content, but is not always exact until reaching this point of the process, where both the done qtys (both UoM and packagings) are measured and get real values.
- Added compute and inverse on `stock.move` for simple scenarios where one move = one move line.
- Add all this on all reports and views.

This change also opens the door to be able to get a real inventory measured in product packagings. That's not implemented in this MVP, but the idea is recorded.

@moduon MT-5531

2024-04-09 23:35 UTC, Shide requested changes

2024-04-09 23:35 UTC, Shide commented on stock_move_packaging_qty/tests/test_stock_move_packaging_qty.py
> +        picking.action_set_quantities_to_reservation()
Assign picking before this line

```suggestion
        picking.action_assign()
        picking.action_set_quantities_to_reservation()
```

2024-04-10 05:46 UTC, rousseldenis commented on stock_move_packaging_qty/__manifest__.py
> +    "development_status": "Alpha",
Be careful as if there are some depending modules on this, they are becoming Alpha too (and possible errors in pre-commit).

2024-04-10 05:50 UTC, rousseldenis requested changes

2024-04-10 05:50 UTC, rousseldenis commented on stock_move_packaging_qty/models/stock_move.py
> +            move.product_packaging_qty_done = sum(
IMHO a read_group with aggregate function is better.

2024-04-10 05:50 UTC, rousseldenis commented on stock_move_packaging_qty/models/stock_move.py
> +            if line.qty_done != line.reserved_uom_qty:
Please use float_compare

2024-04-10 05:51 UTC, rousseldenis commented
@yajo Could you check tests also ?

2024-04-10 07:31 UTC, Shide requested changes

2024-04-10 07:31 UTC, Shide commented on stock_move_packaging_qty/tests/test_stock_move_packaging_qty.py
> +        picking.action_set_quantities_to_reservation()
No need to test if `action_set_quantities_to_reservation()` is done correctly. Uses another fields that are not established in picking/move and the default values maybe differ from you expect.

```suggestion
        picking.move_line_ids[0].qty_done = picking.move_line_ids[0].reserved_uom_qty
```

2024-04-10 08:03 UTC, yajo reviewed
All attended, thanks. Could you review again?

2024-04-10 08:03 UTC, yajo commented on stock_move_packaging_qty/__manifest__.py
> +    "development_status": "Alpha",
AFAICS there are no others depending on this one. However I'll drop this change, as I don't know if it's in a different status for the original authors.

2024-04-10 08:03 UTC, yajo commented on stock_move_packaging_qty/models/stock_move.py
> +            move.product_packaging_qty_done = sum(
That would be a performance improvement if I had a domain to search for lines, because then I could just group all the logic in a single query.

In the case at hand, I need to loop over moves to call `_get_move_lines()` once per move. At this point, all data should be already prefetched by the ORM.

The computing done by python is very light (just a sum). Probably lighter than forcing one extra query per loop. So I don't think that would improve performance here. Actually, it could make it worse.

In any case, if we see later that there's an impact, it'll be easier to fine-tune after getting real performance graphs.

2024-04-10 08:06 UTC, Shide approved these changes

2024-04-10 11:27 UTC, Gelojr approved these changes
LGTM Nice Job @yajo 
https://www.loom.com/share/179c2eef8bc842d2b9b9b9a14b49b84e?sid=53ed3b2c-2dca-4302-bea9-b679d5168669

2024-04-11 12:15 UTC, rafaelbn approved these changes
👍🏼 Great improvement!

2024-04-11 12:19 UTC, rafaelbn commented
@rousseldenis @LoisRForgeFlow can we merge? 😄 ❤️

2024-04-11 12:26 UTC, rousseldenis approved these changes

2024-04-12 08:58 UTC, rafaelbn commented
/ocabot merge minor

2024-04-12 09:05 UTC, merged