[FIX] stock_move_packaging_qty: add packaging qty reserved and computes
OCA/stock-logistics-warehouse pull request #2011
Opened 2024-04-25 09:23 UTC by EmilioPascual

- Add packaging qty reserved in stock move line with compute to know packaging reserved when reserved.
- Add compute to packaging qty done: When update qty done, calculate packaging qty done.

@yajo @Shide @rafaelbn @Gelojr please review.

MT-5861 @moduon

2024-04-25 09:34 UTC, Shide requested changes

2024-04-25 09:34 UTC, Shide commented on stock_move_packaging_qty/models/stock_move_line.py
> +            )
UoM of product_packaging is always the same as product UoM

```suggestion
            line.product_packaging_qty_reserved = float_round(
                line.reserved_uom_qty / line.product_packaging_id.qty,
                precision_rounding=line.product_uom_id.rounding,
            )
```

2024-04-25 09:34 UTC, Shide commented on stock_move_packaging_qty/models/stock_move_line.py
> +            )
Same as above

```suggestion
            line.product_packaging_qty_done = float_round(
                line.qty_done / line.product_packaging_id.qty,
                precision_rounding=line.product_uom_id.rounding,
            )
```

2024-04-26 06:57 UTC, Shide approved these changes

2024-04-26 08:12 UTC, yajo requested changes

2024-04-26 08:12 UTC, yajo commented on stock_move_packaging_qty/views/stock_move_line_view.xml
> +                        groups="product.group_stock_packaging"
issue: add this `groups` to the parent div.

2024-04-26 08:12 UTC, yajo commented on stock_move_packaging_qty/views/stock_move_line_view.xml
> +                    attrs="{'invisible': [('state', '=', 'done')]}"
issue: missing `groups`

2024-04-26 08:12 UTC, yajo commented on stock_move_packaging_qty/models/stock_move_line.py
> +            )
However, it doesn't have to be the same as the UoM in the `stock.move.line`, right? That is what he's handling here AFAICS.

2024-04-26 08:12 UTC, yajo commented on stock_move_packaging_qty/models/stock_move_line.py
> +            if not line.product_packaging_id or not line.product_packaging_id.qty:
```suggestion
            if not line.product_packaging_id.qty:
```

2024-04-26 08:12 UTC, yajo commented on stock_move_packaging_qty/models/stock_move_line.py
> +            )
issue: IIUC you have to keep in mind the conversion between the line uom and the packaging uom.

For that, you can get the data from `reserved_qty` instead, [which is always in the same UoM as the product](https://github.com/odoo/odoo/blob/1d55662f424911873cb2ddcb99e3caf37f43294e/addons/stock/models/stock_move_line.py#L128-L129) (and thus the packaging).

```suggestion
            line.product_packaging_qty_reserved = float_round(
                line.reserved_qty / line.product_packaging_id.qty,
                precision_rounding=line.product_uom_id.rounding,
            )
```

2024-04-26 08:12 UTC, yajo commented on stock_move_packaging_qty/models/stock_move_line.py
> +    @api.depends("product_packaging_id", "product_uom_id", "reserved_uom_qty")
issue: see below

```suggestion
    @api.depends("product_packaging_id", "product_uom_id", "reserved_uom_qty", "reserved_qty")
```

2024-04-26 08:41 UTC, Shide commented
@yajo all fixes attended

2024-04-26 09:18 UTC, yajo approved these changes
/ocabot merge minor

2024-04-26 09:26 UTC, merged