[16.0][ADD] stock_picking_location_check
OCA/stock-logistics-warehouse pull request #2040
Opened 2024-05-20 05:43 UTC by AungKoKoLin1997

This module intends to ensure the internal location consistency between the picking and its stock move lines at the time of validation.

@qrtl QT4063

2024-05-25 04:49 UTC, yostashiro approved these changes
Code review.

2024-06-09 09:47 UTC, yostashiro requested changes

2024-06-09 09:47 UTC, yostashiro commented on stock_picking_location_check/models/stock_picking.py
> +            )
```suggestion
            pick._check_location_consistency(pick.location_id, line_source_locations)
            pick._check_location_consistency(
                pick.location_dest_id, pick.move_line_ids.location_dest_id
            )
```

2024-06-11 02:44 UTC, yostashiro approved these changes

2024-06-11 02:57 UTC, kanda999 approved these changes
Functional review: LGTM

2025-03-12 04:31 UTC, AungKoKoLin1997 commented
@oca/stock-logistics-warehouse-maintainers
Is is possible to take a look at this new module?

2025-03-12 08:18 UTC, rousseldenis commented on stock_picking_location_check/models/stock_picking.py
> +                if not getattr(line.move_id, "is_subcontract", False)
Why is `is_subcontract` field here as there is no dependency on `mrp_subcontracting`. If you have problem with that, a glue module is necessary.

2025-03-12 08:19 UTC, rousseldenis commented on stock_picking_location_check/models/stock_picking.py
> +                    lambda line: line.qty_done > 0
A `float_compare()`  is necessary here.

2025-03-12 08:29 UTC, rousseldenis commented on stock_picking_location_check/readme/CONTEXT.md
> +Users sometimes change locations (location_id/location_dest_id) in the picking after
In standard, it is not possible to select a location (dest  or source) that is not the same or child as the picking one (replicated on stock.move level) and then on move lines.

Do you have particular addons that change that behaviour ?

I've tested on runbot a case where I changed an internal transfer from Stock to Stock to WH to Stock (after reservation):

Move line:

![image](https://github.com/user-attachments/assets/f16581ed-056b-4965-adb3-dc239cfd26b9)


Move:

![image](https://github.com/user-attachments/assets/6d09a960-a30d-4235-9172-12f61170d498)


That is coherent.

Could you explain your use case ?

2025-03-12 09:42 UTC, AungKoKoLin1997 commented on stock_picking_location_check/models/stock_picking.py
> +                if not getattr(line.move_id, "is_subcontract", False)
If `mrp_subtcontracting` was installed in the odoo environment, we want to filter out these subcontracted move lines because they are coming from `subcontracting location` and their location and picking's location will never be the same. Then, I think `getattr` is enough for this and we don't need to depend on `mrp_subcontracting`.

2025-03-12 09:42 UTC, AungKoKoLin1997 commented on stock_picking_location_check/readme/CONTEXT.md
> +Users sometimes change locations (location_id/location_dest_id) in the picking after
This is the example use case we want to use.

https://github.com/user-attachments/assets/e4a9a25f-a002-4c39-805a-10113b88df1a

2025-03-13 02:01 UTC, AungKoKoLin1997 commented on stock_picking_location_check/models/stock_picking.py
> +                    lambda line: line.qty_done > 0
Done!

2026-07-23 13:18 UTC, rousseldenis approved these changes
Ok, I see. That is fixed in v17

2026-07-23 13:19 UTC, rousseldenis commented
/ocabot merge nobump

2026-07-23 13:43 UTC, rousseldenis commented
@sbidoul

2026-07-23 13:55 UTC, sbidoul commented
name reserved on pypi

2026-07-23 13:57 UTC, rousseldenis commented
/ocabot merge nobump

2026-07-23 14:09 UTC, merged