[8.0] [NEW] stock_orderpoint_procure_uom
OCA/stock-logistics-warehouse pull request #209
Opened 2016-10-24 16:06 UTC by jbeficent

=====================
Stock Procurement UoM
=====================

This module allows users users to define what unit of measure should be used
in procurements created from minimum stock rules.

A typical use case would be a product that is stocked in centimeters, and
needs to be restocked in meters from another warehouse. When the picking is
created, the quantity to be transferred will be expressed in meters, making
it easier for the people responsible for the transfers to understand the
requirement.

2016-10-24 16:08 UTC, pedrobaeza commented
Name should be _stock_warehouse_orderpoint_uom_, don't you think?

2016-10-24 16:20 UTC, jbeficent commented
Hmm, yes, you're right. Now changing it.

2016-10-24 16:38 UTC, jbeficent commented
When using the run_scheduler()
https://travis-ci.org/OCA/stock-logistics-warehouse/jobs/170173383#L971

Not sure why. the standard odoo module also run the scheduler in tests:
https://github.com/odoo/odoo/blob/8.0/addons/stock/tests/test_resupply.py#L37

2016-10-24 16:43 UTC, pedrobaeza commented
There shouldn't be a problem with that if you use it correctly. Maybe you should mask your behavior while executing the rest of the tests. See https://github.com/OCA/bank-payment/blob/8.0/account_payment_transfer_reconcile_batch/models/payment_order.py#L28

2016-10-24 16:53 UTC, jbeficent commented
Ok, fixed. Thanks again @pedrobaeza !!

2016-10-24 16:54 UTC, JordiBForgeFlow commented
I was incorrectly calling super() on a test method :S

2016-10-25 07:12 UTC, andhit-r requested changes
Functionality: :+1: tested on runbot
Code: waiting for green travis

2016-10-25 07:12 UTC, andhit-r commented on stock_orderpoint_uom/__openerp__.py
> +    "website": "https://www.odoo-community.org",
Not your company website?

2016-10-25 07:12 UTC, andhit-r commented on stock_orderpoint_uom/__openerp__.py
> +    'application': True,
Is it really need to be an aplication?

2016-10-25 14:17 UTC, jbeficent commented on stock_orderpoint_uom/__openerp__.py
> +    'application': True,
Removed that.

2016-10-25 14:17 UTC, JordiBForgeFlow commented on stock_orderpoint_uom/__openerp__.py
> +    "website": "https://www.odoo-community.org",
Hmm, not in this case.

2016-10-26 16:26 UTC, AaronHForgeFlow reviewed
The rest looks fine, Both the runbot and the code.

2016-10-26 16:26 UTC, aheficent commented on stock_orderpoint_uom/models/procurement_order.py
> +    def onchange_product_id(self):
I'm getting an error in runbot when creating a new procurement order and selecting a product, in the on_change method.

2016-10-26 17:25 UTC, jbeficent commented
fixed. @aheficent @pedrobaeza Can you approve?

2016-10-26 17:32 UTC, AaronHForgeFlow approved these changes
The error I commented is fixed. So :+1:

2016-10-26 22:53 UTC, andhit-r approved these changes
:+1:

2016-11-11 14:34 UTC, merged