[15.0][FIX] stock_inventory: Resolve error when applying inventory with multiple adjustments in the same location
OCA/stock-logistics-warehouse pull request #2120
Opened 2024-07-26 12:10 UTC by JoanSForgeFlow

[FIX] stock_inventory: Resolve error when applying inventory with multiple adjustments in the same location.

Error resolved:

```
  File "/home/joan/odoo/15.0/odoo/odoo/models.py", line 5243, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/joan/odoo/15.0/odoo/odoo/http.py", line 658, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/joan/odoo/15.0/odoo/odoo/http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: Expected singleton: stock.inventory(105, 104)
```

2024-07-26 12:23 UTC, rousseldenis commented
@JoanSForgeFlow A test case should be great in order to prevent regressions. Thanks

2024-07-26 13:21 UTC, rousseldenis commented on stock_inventory/tests/test_stock_inventory.py
> +        self.quant3.action_apply_inventory()
@JoanSForgeFlow Shouldn't be the test call `_action_apply_inventory`on the recordset composed by quant 3 and 4 ?

2024-07-26 13:31 UTC, LoisRForgeFlow requested changes
Still able to reproduce the error:

![image](https://github.com/user-attachments/assets/1957b95a-d31c-474c-8f5e-e5485e85e3e9)

2024-07-26 13:59 UTC, rousseldenis commented on stock_inventory/models/stock_quant.py
> +            adjustment = rec.stock_inventory_ids.filtered(
@JoanSForgeFlow This could lead to several adjustements.

Error on line 43

2024-07-30 11:50 UTC, LoisRForgeFlow approved these changes
I like this approach, thanks

2024-08-02 12:24 UTC, AaronHForgeFlow approved these changes
Code review LGTM

2024-08-06 08:05 UTC, LoisRForgeFlow commented
/ocabot merge minor

2024-08-06 08:17 UTC, merged