[8.0] Stock Operation Type Location
OCA/stock-logistics-warehouse pull request #215
Opened 2016-11-01 11:43 UTC by mikevhe18

Changelog : 

- Fixing issue when allowed source/destination location has only one data and the same as default source/destination location

- Adds the possibility to filter location of transfer wizard using the same behaviour

2016-11-01 13:05 UTC, andhit-r requested changes
Code Review: minor comments inline. Coverage decreased but nothing related to this PR
Functional Review: Ok. Tested on runbot

2016-11-01 13:05 UTC, andhit-r commented on stock_operation_type_location/__openerp__.py
> +    'version': '8.0.1.1.1',
8.0.1.1.0 enough

2016-11-01 13:05 UTC, andhit-r commented
@azmimr67 @m-sani please review

2016-11-02 01:53 UTC, m-sani commented
tested :+1:

2016-11-08 02:12 UTC, mikevhe18 commented
Hello @gurneyalex , @jgrandguillaume , @rousseldenis, @pedrobaeza 
Would you kindly review this PR ?

Thanks in Advance

2016-11-08 10:18 UTC, gurneyalex commented on stock_operation_type_location/models/stock_move.py
> +            scr_id = picking_type.default_location_src_id.id
can we take the opportunity of this PR to fix the typo and `s/scr_id/src_id/` ?

2016-11-08 10:18 UTC, gurneyalex commented on stock_operation_type_location/wizard/stock_transfer_details.py
> +                domain_destinationloc = "[]"
you could much simplify this block by first initializaing domain_sourceloc and domain_destinationloc to "[]" and having two blocks changing the value `if loc:` and `if dest_loc:`

2016-11-08 10:35 UTC, rousseldenis reviewed
@mikevhe18 Tested on runbot ok. Minor comment

2016-11-08 10:35 UTC, rousseldenis commented on stock_operation_type_location/wizard/stock_transfer_details.py
> +        context = self._context
Should use self.env.context

2016-11-09 00:31 UTC, mikevhe18 commented
Fixed. Thanks @gurneyalex @rousseldenis.

2016-11-09 06:48 UTC, rousseldenis approved these changes
:+1

2016-11-09 07:23 UTC, azmimr67 commented
Has been tested on runboot :+1:

2016-11-10 12:59 UTC, gurneyalex approved these changes

2016-11-10 12:59 UTC, merged