[16.0][FIX] stock_valuation_layer_accounting_date: prevent tests failed for some timezone
OCA/stock-logistics-warehouse pull request #2159
Opened 2024-09-20 12:09 UTC by AungKoKoLin1997

This fix is to address the issue for failing tests depending on timezone.

Related: https://github.com/OCA/stock-logistics-warehouse/pull/2139#issuecomment-2299186125

@qrtl

2024-09-20 14:02 UTC, yostashiro requested changes

2024-09-20 14:02 UTC, yostashiro commented on stock_valuation_layer_accounting_date/tests/test_stock_valuation_layer_accounting_date.py
>          self.product1.product_tmpl_id.categ_id.property_valuation = "real_time"
We shouldn't be changing the intention of the test.
```suggestion
    @freeze_time("2022-12-02 23:00:00")
    def test_svl_accounting_date_real_time(self):
        self.product1.categ_id.property_valuation = "real_time"
        self.env.user.tz = "Asia/Tokyo"
```

2024-09-20 14:02 UTC, yostashiro commented on stock_valuation_layer_accounting_date/tests/test_stock_valuation_layer_accounting_date.py
> +        self.assertEqual(valuation_layer.accounting_date, date(2022, 12, 2))
Revert this change.

2024-09-21 02:01 UTC, yostashiro approved these changes

2024-09-23 07:16 UTC, rousseldenis approved these changes

2024-09-25 15:09 UTC, AungKoKoLin1997 commented
@rousseldenis Can we get this PR merged?

2024-12-31 11:48 UTC, jbaudoux approved these changes

2024-12-31 11:48 UTC, jbaudoux commented
/ocabot merge patch

2025-01-17 09:34 UTC, AungKoKoLin1997 commented
@jbaudoux I think merging was not successful. Can you please try again?

2025-01-17 11:02 UTC, jbaudoux commented
/ocabot merge patch

2025-01-17 11:07 UTC, merged