[ADD] [9.0] [stock_quant_reserved_qty_uom]
OCA/stock-logistics-warehouse pull request #216
Opened 2016-11-04 18:22 UTC by jbeficent

============================
Stock Quant Reserved Qty UoM
============================

This module allows to display the quantity of a quant in the unit of measure
defined in the reservation move.

2016-12-07 10:58 UTC, rousseldenis requested changes

2016-12-07 10:58 UTC, rousseldenis commented on stock_quant_reserved_qty_uom/__openerp__.py
> +    'version': '8.0.1.0.0',
@jbeficent Could you please change version (runbot failed to build) for tests ?

2017-01-18 08:37 UTC, rousseldenis requested changes

2017-01-18 08:37 UTC, rousseldenis commented on stock_quant_reserved_qty_uom/tests/test_stock_quant_reserved_qty_uom.py
> +class TestStockQuantReservedQtyUom(TransactionCase):
@jbeficent It seems that assert test is not executed (if I understand codecoverage result). Can you check ?

2017-02-27 09:00 UTC, jbeficent commented
@mreficent can you review the comments made by @rousseldenis on this one?

2017-03-03 12:30 UTC, mreficent commented
Checked and fixed.

2017-03-03 12:31 UTC, MiquelRForgeFlow approved these changes
Tested on local :+1:

2017-03-14 22:18 UTC, jbeficent commented
@darshan-serpent @lreficent @gceficent can you review?

2017-03-15 16:08 UTC, LoisRForgeFlow approved these changes
Code review, LGTM :+1:

2017-03-15 17:00 UTC, gmeficent approved these changes
Functional review on local, works as described :+1:

2017-03-15 17:03 UTC, rousseldenis approved these changes
:+1:

2017-03-15 17:27 UTC, merged