[8.0] [stock_warehouse_orderpoint_stock_info]
OCA/stock-logistics-warehouse pull request #217
Opened 2016-11-07 12:51 UTC by jbeficent

This is a port from OdooMRP. https://github.com/odoomrp/odoomrp-utils/tree/8.0/stock_warehouse_orderpoint_stock_info

2016-11-07 12:51 UTC, jbeficent commented
cc @mikelarre, @anajuaristi @pedrobaeza

2016-11-07 15:24 UTC, jbeficent commented
@pedrobaeza @anajuaristi You cannot store the field `available` (https://github.com/OCA/stock-logistics-warehouse/pull/217/files#diff-954246850314d5d706bb6495fd5f4400R45) because the computation depends on field 'product_location_qty', which is not an stored fields, and depends on the quantity on hand.

2016-11-07 15:34 UTC, jbeficent commented
@pedrobaeza @anajuaristi I removed the field 'is enough product available?' (https://github.com/odoomrp/odoomrp-utils/blob/8.0/stock_warehouse_orderpoint_stock_info/models/stock_warehouse_orderpoint.py#L36) because it was incorrectly defined.

It was meant to be used to search for products that do not meet the minimum, and was defined as a stored field. However after running tests we found that this stored field was not being recomputed correctly, because it's computation depends on field 'product_location_qty', which is not a stored field.

If you want to be able to apply such field you have to provide the correct dependencies in the method. It's a complex topic, and we're also addressing it, but will need to be done in a separate module, in any case.

2016-11-07 15:37 UTC, pedrobaeza commented
I don't know this module, Jordi. I let in Ana's side.

2016-11-07 16:19 UTC, oihane commented
I don't remember exactly what was it meant to do. As @jbeficent said is only used in tree view, I think is a way to access easily to those that have available qty less than minimum stock.

It was asked to include by @pedrobaeza https://github.com/odoomrp/odoomrp-utils/pull/27#issuecomment-74638920

2016-11-07 16:22 UTC, jbeficent commented
@oihane It is used in the search. And that's where it's critical, because searching for this field will for sure drive wrong results.

2016-11-07 16:25 UTC, pedrobaeza commented
Wow, I didn't even remember that I reviewed this module... bad memory. Anyways, being in odoomrp-utils, you know that I deny of modules from that second repo, hehe.

2016-11-07 16:31 UTC, jbeficent commented
In any case, I removed that field. You can check the PR and provide your feedback.

2016-11-07 16:36 UTC, oihane requested changes

2016-11-07 16:36 UTC, oihane commented on stock_warehouse_orderpoint_stock_info/models/stock_warehouse_orderpoint.py
> +    def _compute_product_available(self):
You can remove this part as it does not have `available` field.

2016-11-07 16:58 UTC, oihane approved these changes
:+1:  LGTM

2016-11-07 17:00 UTC, mikelarre commented
:+1:  when travis goes green

2016-11-08 09:06 UTC, jbeficent commented
This one is ready to merge.

2016-11-10 15:16 UTC, merged