[17.0] [MIG] stock_quant_reservation_info:  Migration to 17.0
OCA/stock-logistics-warehouse pull request #2206
Opened 2024-11-28 10:16 UTC by MeritxellAForgeFlow

Migration to 17.0 
@ForgeFlow

2024-11-28 10:20 UTC, JordiMForgeFlow commented on stock_quant_reservation_info/__manifest__.py
> +    "version": "17.0.1.0.1",
reset to 17.0.1.0.0

2024-11-28 10:33 UTC, DavidJForgeFlow requested changes
Works fine! But there is a small detail for this version!

2024-11-28 10:33 UTC, DavidJForgeFlow commented on stock_quant_reservation_info/views/stock_quant.xml
In this version there is two views for the quants, one going throught Inventory -> Operations -> Inventory Adjustments (`stock.view_stock_quant_tree_inventory_editable`) and the other one going throught Inventory -> Products -> Products and clicking on the smart button Onhand inside of a product (`stock.view_stock_quant_tree_editable`) make sure the changes of the modules reflect on both views!

2024-11-28 12:25 UTC, AaronHForgeFlow commented on stock_quant_reservation_info/views/stock_quant.xml
I also miss the button in the quant list view that is open when I click on Inventory -> Reporting -> Locations. It is the quant tree view grouped by product and location:
![image](https://github.com/user-attachments/assets/032791d4-d3b0-4196-b9df-8ef0be34c668)

2024-11-28 12:58 UTC, rousseldenis commented
/ocabot migration stock_quant_reservation_info

2024-11-29 09:42 UTC, AaronHForgeFlow approved these changes
Functional review :+1:

2024-12-03 09:16 UTC, JoanSForgeFlow approved these changes

2024-12-05 09:30 UTC, rousseldenis approved these changes

2024-12-05 09:41 UTC, LoisRForgeFlow requested changes
Functional review

I miss the button to show reservation info

![image](https://github.com/user-attachments/assets/cbd4e73f-067a-415c-b915-ddd1c7517691)

2024-12-09 08:46 UTC, LoisRForgeFlow approved these changes
Now it LGTM!

2024-12-09 08:47 UTC, LoisRForgeFlow commented
/ocabot merge nobump

2024-12-09 10:03 UTC, merged