[IMP] stock_location_last_inventory_date: Make last_inventory_data storeable
OCA/stock-logistics-warehouse pull request #2222
Opened 2024-12-17 09:40 UTC by mt-software-de

This allows to search this field

2024-12-17 10:04 UTC, mt-software-de commented
@hailangvn @sebalix @simahawk 
Could you maybe review this one, since you did the migration for it?
https://github.com/OCA/stock-logistics-warehouse/pull/1261

2024-12-17 10:13 UTC, mt-software-de commented
cc @i-vyshnevska @jbaudoux

2024-12-17 12:40 UTC, vuwnevska commented on stock_location_last_inventory_date/models/stock_location.py
>              ]
search method was more efficient

2024-12-17 12:47 UTC, jbaudoux requested changes
You can make an inventory of a location without making any inventory line. I would have not changed that concept.
In newer versions, it's updating the date when the inventory is posted. You could go that way and make a migration script of the initialization of the field.

2024-12-17 12:47 UTC, jbaudoux commented on stock_location_last_inventory_date/models/stock_location.py
> +                if line.state == "done"
can move to fields definition `done_inventory_line_ids` as a domain

2024-12-17 15:27 UTC, mt-software-de commented on stock_location_last_inventory_date/models/stock_location.py
> +                if line.state == "done"
The last_inventory_date will be now set on action_done.
But still i am using the locations set on `stock.inventory.line`.
You can also create a `stock.inventory` without setting location_ids. 
The lines should be created by `_action_start` 
(https://github.com/odoo/odoo/blob/cc0060e889603eb2e47fa44a8a22a70d7d784185/addons/stock/models/stock_inventory.py#L170).
If the lines aren't created, then they should be created manually.

This is then now the same as it is in newer versions. `stock.inventory.line` is removed and just `stock.quant` is used. 
In v14 the method `_get_inventory_lines_values`
(https://github.com/odoo/odoo/blob/cc0060e889603eb2e47fa44a8a22a70d7d784185/addons/stock/models/stock_inventory.py#L297)
is getting the data from `stock.quant`.

2024-12-18 12:54 UTC, vuwnevska approved these changes

2024-12-18 12:54 UTC, vuwnevska commented on stock_location_last_inventory_date/__manifest__.py
> +    "version": "14.0.1.0.1",
```suggestion
    "version": "14.0.1.1.0",
```

2024-12-18 16:16 UTC, jbaudoux commented on stock_location_last_inventory_date/hooks.py
> +    )
This can load millions of lines. I think you better do it with one SQL query doing the update without loading anything in odoo cache

2024-12-18 16:16 UTC, jbaudoux commented on stock_location_last_inventory_date/__manifest__.py
> +    "version": "14.0.1.0.1",
I would even put it as a major change
```suggestion
    "version": "14.0.2.0.0",
```

2024-12-18 18:46 UTC, mt-software-de commented on stock_location_last_inventory_date/hooks.py
> +    )
Yes of course you are right.

2024-12-18 20:03 UTC, mt-software-de commented on stock_location_last_inventory_date/__manifest__.py
> +    "version": "14.0.1.0.1",
done

2025-01-08 20:44 UTC, jbaudoux approved these changes

2025-01-22 09:02 UTC, mt-software-de commented
can this be merged?

2025-01-22 09:11 UTC, jbaudoux commented
/ocabot merge nobump

2025-01-22 09:27 UTC, merged