[9.0][ADD] stock_available_global: New module
OCA/stock-logistics-warehouse pull request #225
Opened 2016-11-25 17:21 UTC by carlosdauden

This module adds new fields to show product stock in all companies.
In product forms appear two new smarts buttons *On Hand* and *Forecast* witch computes all companies stock.

@Tecnativa

2016-11-25 18:48 UTC, pedrobaeza requested changes

2016-11-25 18:48 UTC, pedrobaeza commented on stock_available_global/README.rst
> +In product forms appear two new smarts buttons *On Hand* and *Forecast* witch
s/witch/which

2016-11-25 18:48 UTC, pedrobaeza commented on stock_available_global/models/product_product.py
> +        for product in self:
Better to do:
```
for product in self.sudo():
```
and you save the rest of the sudos.

2016-11-25 18:48 UTC, pedrobaeza commented on stock_available_global/models/product_template.py
> +        for product in self:
`for product in self.sudo():`

2016-11-25 18:48 UTC, pedrobaeza commented on stock_available_global/views/product_product_view.xml
> +            <xpath expr="//button[@name='%(stock.action_stock_level_forecast_report_product)d']"
Is this showing all the quants?

2016-11-25 18:56 UTC, carlosdauden commented on stock_available_global/views/product_product_view.xml
> +            <xpath expr="//button[@name='%(stock.action_stock_level_forecast_report_product)d']"
No, only shows actual company quants.

2016-11-25 19:00 UTC, pedrobaeza commented on stock_available_global/views/product_product_view.xml
> +            <xpath expr="//button[@name='%(stock.action_stock_level_forecast_report_product)d']"
Then I think it's better not to offer the clickable possibility and only show data.

2017-07-27 17:10 UTC, pedrobaeza commented
@carlosdauden please make the requested changes.

2018-06-28 18:56 UTC, pedrobaeza commented
Closing as target branch has changed

2018-06-28 18:56 UTC, closed without merging