[9.0]-[mig]-stock_orderpoint_manual_procurement
OCA/stock-logistics-warehouse pull request #234
Opened 2016-12-23 10:49 UTC by lreficent

Stock Orderpoint Manual Procurement
===================================

This module allows users to manually start procurements from the list of
reordering rules, based on the quantity that is recommended to be procured.

Usage
=====

Go to 'Inventory > Inventory Control > Reordering Rules' and review the
quantity recommended to be procured. You can now start the procurement for a
single or a list of reordering rules.

The recommended quantity to procure is adjusted to the procurement unit of
measure indicated in the reordering rule.

If you want users to be able to change the recommended quantity to procure,
you should assign them to the security group 'Change quantity in manual
procurements from reordering rules', under 'Settings / Users / Users'.

2016-12-23 11:02 UTC, jbeficent commented
Depends on https://github.com/OCA/stock-logistics-warehouse/pull/233

2016-12-23 16:25 UTC, JordiBForgeFlow approved these changes
Technical and functional review :+1:

2017-01-20 08:43 UTC, aheficent commented on stock_orderpoint_manual_procurement/__openerp__.py
> +    'application': True,
Is it not a single module?
Modules extend functionality. An app is a collection of modules, isn't it?

2017-01-20 08:58 UTC, AaronHForgeFlow requested changes
I'm getting this qty when I procure less than the recommended qty:
![image](https://cloud.githubusercontent.com/assets/19620251/22142549/ea95a6b6-def6-11e6-85ad-1d5be97612cd.png)

2017-01-20 09:12 UTC, lreficent commented
@aheficent I cannot reproduce the error. But I think it can be something related with rounding precision of the uom.
![image](https://cloud.githubusercontent.com/assets/23449160/22143034/e3a51e3e-def8-11e6-9ff6-3273c673814e.png)
In that case you probably have to set up a rounding of a whole unit.

2017-01-20 09:13 UTC, lreficent commented on stock_orderpoint_manual_procurement/__openerp__.py
> +    'application': True,
Yes, you likely right. I'll fix it

2017-01-20 09:17 UTC, aheficent commented
Yes you are right. By default the rounding precision for units of measure is 0.001, which is wrong.

2017-01-20 09:20 UTC, AaronHForgeFlow approved these changes
LGTM now :+1:

2017-01-20 11:04 UTC, andhit-r approved these changes
:+1:

2017-01-20 11:09 UTC, jbeficent commented
@lreficent thanks. Can you squash your own commits? https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests

2017-01-20 12:55 UTC, merged