[9.0][stock_inventory_revaluation] Allow to delete quants
OCA/stock-logistics-warehouse pull request #270
Opened 2017-03-29 09:41 UTC by jbeficent

Now when an inventory revaluation has been posted for a product that has real price costing methods, if you revaluate some quants and then these quants need to be deleted afterwards, the user gets an error.

Deleting quants is done automatically by the system in some cases. For example, when you unreserve a delivery order and serveral quants are merged together.

2017-03-29 09:41 UTC, jbeficent commented
@lreficent @gmeficent can you review?

2017-03-30 16:26 UTC, lreficent commented
Travis says that the tests are failing: <code>stock_inventory_revaluation.tests.test_stock_inventory_revaluation: ERROR</code>

2017-04-26 11:02 UTC, gmeficent requested changes
I couldn't replicate the User Error on runbot and the added test fails due to constraints so I can't quite tell if it works.

2017-04-26 11:02 UTC, gmeficent commented on stock_inventory_revaluation/tests/test_stock_inventory_revaluation.py
> +            quant.unlink()
Maybe using .sudo() would solve the issue.

![image](https://cloud.githubusercontent.com/assets/25898232/25431229/fcae10b6-2a7f-11e7-9b2f-f2b06f56ebd9.png)

2017-05-29 14:05 UTC, lmignon requested changes

2017-05-29 14:05 UTC, lmignon commented on stock_inventory_revaluation/tests/test_stock_inventory_revaluation.py
> +            quant.unlink()
@jbeficent @gmeficent It's not allowed by odoo to call unlink on a quant... https://github.com/odoo/odoo/blob/9.0/addons/stock/stock.py#L746
UNLESS you call unlink with `force_unlink=True` into the context 
```python
quants..with_context(force_unlink=True).unlink
```
You don't need to loop on the quants to call unlink...

2017-06-29 08:49 UTC, jbeficent commented
Thanks for your feedback @lmignon. Travis is green now.

2017-06-29 10:32 UTC, gmeficent approved these changes
Seems like that solves the issue, LGTM :+1:

2017-06-29 11:41 UTC, LoisRForgeFlow approved these changes
Code review LGTM :+1:

2017-06-29 12:02 UTC, merged