[10.0][MIG] stock_inventory_line_price: to v10
OCA/stock-logistics-warehouse pull request #276
Opened 2017-04-22 19:06 UTC by lasley

* Rename manifest
* Bump versions
* Openerp references to Odoo

v9 migration is in  #275

2017-05-08 06:35 UTC, rousseldenis approved these changes
Code review

2017-07-19 03:58 UTC, congdpt approved these changes

2017-08-03 10:39 UTC, tafaRU approved these changes
Only some nitpicking in the README.rst otherwise :+1:

2017-08-03 10:39 UTC, tafaRU commented on stock_inventory_line_price/README.rst
> +.. image:: https://odoo-community.org/website/image/ir.attachment/5784_f2813bd/datas
this part should be moved under https://github.com/OCA/maintainer-tools/blob/master/template/module/README.rst#usage

2017-08-03 15:20 UTC, lasley commented on stock_inventory_line_price/README.rst
> +.. image:: https://odoo-community.org/website/image/ir.attachment/5784_f2813bd/datas
Hmmm but there isn't a usage section. Does it make sense to add one just for the Runbot link?

2017-11-09 08:33 UTC, rousseldenis commented
@lasley @lreficent Can we move forward on this one ?

2017-11-09 11:26 UTC, lreficent commented on stock_inventory_line_price/views/inventory_view.xml
> +                <attribute name="colors">blue: product_qty != theoretical_qty or theoretical_std_price != standard_price; red: theoretical_qty &lt; 0</attribute>
We are still having the same issue here as in [v9](https://github.com/OCA/stock-logistics-warehouse/pull/275#pullrequestreview-37237048)

2018-04-19 15:24 UTC, rousseldenis requested changes
Code review.

Is someone maintaining this as @lasley won't maybe fix it?

2018-04-19 15:24 UTC, rousseldenis commented on stock_inventory_line_price/models/stock_inventory_line.py
> +        for inventory_line in self:
@lasley You make this method one as the original one is multi.

You'd better write:

```python
moves = self.env['stock.move'].browse() # Real void recordset
equal_lines = self.filtered(lambda l: l.theoretical_std_price==l.standard_price)
non_equal_lines = self - equal_lines
moves = super(StockInventoryLine, equal_lines)._generate_moves()
for line in non_equal_lines:
    line.product_id.standard_price = line.standard_price
moves += super(StockInventoryLine, non_equal_lines)._generate_moves()
return moves
```

Maximum two calls to super comparing to n calls

2018-04-19 15:24 UTC, rousseldenis commented on stock_inventory_line_price/models/stock_inventory.py
> +            product = self.env['product.product'].browse(line['product_id'])
Maybe consider browsing all products at one time to avoid performances problems.

2019-04-27 15:09 UTC, rousseldenis commented
I suppose we can close this soon

2019-04-29 15:48 UTC, lreficent commented
@rousseldenis I think we can do it now, this is old and we all know Lasley is not working in Odoo topics anymore.

2019-04-29 15:48 UTC, closed without merging

2019-04-29 15:54 UTC, rousseldenis commented
> @rousseldenis I think we can do it now, this is old and we all know Lasley is not working in Odoo topics anymore.

:+1: I was waiting because I thought @pedrobaeza has access to his former repos.

2019-04-29 16:50 UTC, pedrobaeza commented
In fact all repository maintainers have access (including you, Denis). You just need to push to that remote.