[9.0][FIX][stock_inventory_lockdown] not allowing adjustments in locations with negative quants
OCA/stock-logistics-warehouse pull request #304
Opened 2017-06-27 10:31 UTC by jbeficent

We found that the current design was not allowing to perform inventory adjustments on a location that had negative quants.

We have done a refactoring of the module to perform lockdown validations using constraint in stock move instead of checks in quants. This will allow for a more robust lockdown mechanism, and still make it possible to perform inventory adjustments in the locked location. Also resolves an outstanding issue related to the previous design not allowing inventory adjustments where negative quants existed.

cc @StefanRijnhart @Cedric-Pigeon @lmignon @clonedagain

2017-06-28 15:39 UTC, LoisRForgeFlow approved these changes
Code + Functional review :+1:

2017-07-26 16:28 UTC, StefanRijnhart approved these changes
Nice. Interesting use of api.constrains!

2017-07-26 16:32 UTC, MiquelRForgeFlow approved these changes
LGTM

2017-07-27 11:16 UTC, AaronHForgeFlow approved these changes
:+1: Functional test

2017-08-19 10:31 UTC, rousseldenis requested changes
Code review, minor comment

2017-08-19 10:31 UTC, rousseldenis commented on stock_inventory_lockdown/models/stock_move.py
> +        for move in self:
@jbeficent Maybe `for move in self.filtered(lambda m: m.state != 'draft'):`

2017-08-21 08:38 UTC, mreficent commented
@rousseldenis done 😉

2017-08-28 09:13 UTC, lreficent commented
@rousseldenis could you update your review?

2017-08-28 09:24 UTC, rousseldenis approved these changes
:+1: Code review

2017-08-28 12:13 UTC, merged