[IMP] show incoming date of quant, easier to pick
OCA/stock-logistics-warehouse pull request #324
Opened 2017-08-01 07:04 UTC by fanha99

2017-08-19 10:10 UTC, rousseldenis requested changes
Minor comment but :+1:

2017-08-19 10:10 UTC, rousseldenis commented on stock_quant_manual_assign/wizard/assign_manual_quants.py
> +        string='In Date', readonly=True)
@fanha99 Maybe 'Incoming Date' should be more explicit ?

2017-08-21 07:08 UTC, pedrobaeza requested changes
Please change version number according: https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#version-numbers

2017-08-21 08:24 UTC, pedrobaeza approved these changes

2017-08-21 08:26 UTC, rousseldenis approved these changes
:+1: Code review

2017-08-21 08:39 UTC, merged