[11.0] [MIG] account move line product: Migration to 11.0
OCA/stock-logistics-warehouse pull request #354
Opened 2017-11-14 17:28 UTC by VRodrigo

2018-01-17 12:01 UTC, LoisRForgeFlow approved these changes
Code reivew LGTM

Please squash your migration commits into one.

Thanks!

2018-02-28 13:45 UTC, HviorForgeFlow requested changes

2018-02-28 13:45 UTC, hveficent commented on account_move_line_product/README.rst
> +.. image:: https://img.shields.io/badge/license-AGPLv3-blue.svg
change to .png image

2018-02-28 13:45 UTC, hveficent commented on account_move_line_product/README.rst
> +* Odoo Community Association: `Icon <https://github.com/OCA/maintainer-tools/blob/master/template/module/static/description/icon.svg>`_.
change to .png image

2018-02-28 13:45 UTC, hveficent commented on account_move_line_product/README.rst
> +   :target: https://runbot.odoo-community.org/runbot/92/10.0
10.0 -> 11.0 version change

2018-03-18 18:07 UTC, gurneyalex approved these changes

2018-03-19 08:23 UTC, AaronHForgeFlow reviewed
Code seems fine to me, pending for runbot for functional

2018-04-10 09:32 UTC, HviorForgeFlow approved these changes

2018-04-10 09:35 UTC, pedrobaeza commented
There are still comments unattended.

2018-04-18 14:30 UTC, jbeficent commented
@VRodrigo can you address the minor comments? We're almost ready to merge.

2018-12-29 04:09 UTC, emagdalenaC2i commented
@pedrobaeza I think this PR should be closed because this module is already merged in #471

2018-12-29 13:50 UTC, closed without merging