11.0 mig stock orderpoint automatic creation
OCA/stock-logistics-warehouse pull request #429
Opened 2018-05-02 02:47 UTC by andreasdsp

2018-08-27 07:09 UTC, Axel-G commented
How could i support this (and others) modules to get merged?

2018-08-27 07:11 UTC, pedrobaeza commented
Review them: https://odoo-community.org/page/review

2018-08-27 17:40 UTC, Axel-G commented
Sorry. i asking often same, but i want learn it :) i cant start the runbot instance, i dont understood the system . But i test the module on my own testing-instance and it seems ok.

2018-09-28 11:09 UTC, HaraldPanten approved these changes
Functional review

:+1:

2018-10-02 07:49 UTC, LoisRForgeFlow requested changes
Some styling/standars comments. Other than that code looks good.

2018-10-02 07:49 UTC, lreficent commented on stock_orderpoint_automatic_creation/README.rst
> +   :target: https://runbot.odoo-community.org/runbot/153/10.0
11.0

2018-10-02 07:49 UTC, lreficent commented on stock_orderpoint_automatic_creation/__init__.py
> +# -*- coding: utf-8 -*-
this line [is not needed anymore in python 3](https://stackoverflow.com/questions/37048761/coding-utf-8-on-python3/37048998#37048998)

2018-10-02 07:49 UTC, lreficent commented on stock_orderpoint_automatic_creation/__manifest__.py
> +# -*- coding: utf-8 -*-
same for all files

2018-10-02 07:49 UTC, lreficent commented on stock_orderpoint_automatic_creation/__manifest__.py
> +    "website": "http://www.odoomrp.com",
https://github.com/OCA/stock-logistics-warehouse

2018-10-02 07:49 UTC, lreficent commented on stock_orderpoint_automatic_creation/__manifest__.py
> +    "category": "Inventory, Logistic, Storage",
Just `Inventory` is better

2018-10-19 11:15 UTC, HaraldPanten commented
Hi @andreasdsp ,

Any news about this PR?

Thanks!

2018-10-19 11:39 UTC, andreasdsp commented
Hi, 
I'm sorry, i can't continue this because i'm still busy on another project now.
Thanks.

2018-10-30 17:45 UTC, rousseldenis commented
Supersedes by #502

2018-10-30 17:45 UTC, closed without merging