[11.0] [add] stock_warehouse_calendar
OCA/stock-logistics-warehouse pull request #454
Opened 2018-06-28 17:02 UTC by jbeficent

Stock Warehouse Calendar
========================

This module adds a Calendar to the Warehouse. This calendar can then used as
the basis of the proper computation of start/end dates based on lead times in
this and other modules.

In this module, the calendar considered in the computation of start date of
stock moves and pickings created from procurements, where the lead time
is used.

Configuration
=============

* Go to *Settings* and activate the developer mode.

* Go to *Settings > Technical > Resource > Working Time* and define your
  resource calendar.

* Go to *Inventory > Configuration > Warehouse Management > Warehouses*
  and assign the Resource Calendar.

* Go to *Inventory > Configuration > Warehouse Management > Routes* and
  set up the proper delays in the procurement rules where the supply method
  is 'Move'.

Usage
=====

* When a picking is created out of a procurement evaluation (from an
  orderpoint, MTO,...) the calendar is considered in the computation of the
  expected date of the picking and moves. For example, if it takes 1 day to
  execute a stock transfer from another warehouse and it is Monday, the picking
  to resupply will be created with expected start date on the previous Friday,
  if the warehouse operates under a Mo-Fri working calendar.

2018-06-28 20:00 UTC, pedrobaeza requested changes

2018-06-28 20:00 UTC, pedrobaeza commented on stock_warehouse_calendar/models/procurement_rule.py
> +        dt_planned = datetime.strptime(values['date_planned'],
Use `fields.Datetime.from_string`

2018-06-28 20:00 UTC, pedrobaeza commented on stock_warehouse_calendar/data/stock_warehouse_data.xml
> +    <data>
Not needed

2018-06-28 20:01 UTC, pedrobaeza commented
Travis is red

2018-06-29 12:34 UTC, mreficent commented on stock_warehouse_calendar/README.rst
> +  is 'Move'.
```
set up the proper delays in the procurement rules where 'action'
is 'Move From Another Location'.
```

2018-06-29 12:34 UTC, mreficent commented on stock_warehouse_calendar/README.rst
> +
Add:

`* Go to *Inventory > Configuration > Settings* and in *Warehouse* mark 'Multi-Step Routes option'.`

2018-06-29 12:34 UTC, mreficent commented on stock_warehouse_calendar/README.rst
> +.. image:: https://img.shields.io/badge/licence-LGPL--3-blue.svg
`.png`

2018-07-02 10:05 UTC, LoisRForgeFlow approved these changes
Tested locally and it works good! :+1:

2018-07-02 10:07 UTC, lreficent commented on stock_warehouse_calendar/data/stock_warehouse_data.xml
> +        <field name="calendar_id" ref="resource.resource_calendar_std"/>
maybe do not set the calendar by default?

2018-07-02 11:22 UTC, MiquelRForgeFlow approved these changes
LGTM

2018-07-02 11:22 UTC, mreficent commented on stock_warehouse_calendar/__init__.py
> +
this blank line could be removed

2018-07-04 07:57 UTC, lreficent commented
@pedrobaeza Could you update your review?

2018-07-04 08:49 UTC, pedrobaeza approved these changes

2018-07-04 08:50 UTC, merged

2018-07-04 09:53 UTC, lreficent commented
Thanks!