[MIG] stock_orderpoint_generator: Migration to 11.0
OCA/stock-logistics-warehouse pull request #488
Opened 2018-09-27 12:05 UTC by cubells

cc @Tecnativa

2018-09-27 21:47 UTC, pedrobaeza approved these changes

2018-09-28 07:52 UTC, chienandalu requested changes

2018-09-28 07:52 UTC, chienandalu commented on stock_orderpoint_generator/views/orderpoint_template_views.xml
> +                <field name="location_id" groups="stock.group_locations"/>
Shouldn't it be `stock.group_stock_multi_locations`

2018-09-28 07:52 UTC, chienandalu commented on stock_orderpoint_generator/views/orderpoint_template_views.xml
> +                            <field name="location_id" groups="stock.group_locations"/>
Same here with `stock.group_stock_multi_locations`?

2018-09-28 07:52 UTC, chienandalu commented on stock_orderpoint_generator/views/orderpoint_template_views.xml
> +                <field name="warehouse_id" groups="stock.group_locations"/>
`stock.group_stock_multi_locations`

2018-09-28 07:52 UTC, chienandalu commented on stock_orderpoint_generator/views/orderpoint_template_views.xml
> +                <field name="location_id" groups="stock.group_locations"/>
`stock.group_stock_multi_locations`

2018-09-28 07:52 UTC, chienandalu commented on stock_orderpoint_generator/views/orderpoint_template_views.xml
> +                            <field name="warehouse_id" on_change="onchange_warehouse_id(warehouse_id)" widget="selection" groups="stock.group_locations"/>
is this `onchange` attribute necessary anymore?

2018-09-28 10:27 UTC, cubells commented
@chienandalu done.

2018-10-09 07:17 UTC, rousseldenis approved these changes
Code review

2018-10-09 07:17 UTC, rousseldenis commented
@chienandalu Can you update your review ?

2018-10-09 08:04 UTC, chienandalu approved these changes
Great :+1:

2018-10-09 08:13 UTC, merged