[11.0][MIG]stock_orderpoint_automatic_creation
OCA/stock-logistics-warehouse pull request #502
Opened 2018-10-30 16:27 UTC by ValentinVinagre

Finished the PR https://github.com/OCA/stock-logistics-warehouse/pull/429 from @andreasdsp.

2018-10-30 16:34 UTC, rousseldenis commented
@ValentinVinagre so, this supersedes #429 ?

2018-10-30 16:42 UTC, ValentinVinagre commented
yes

2018-10-30 16:49 UTC, rousseldenis commented
Please preserve commit history from previous versions

2018-10-30 17:00 UTC, ValentinVinagre commented
I don't know how do that. Any help?

2018-10-30 17:45 UTC, rousseldenis commented
@ValentinVinagre You can read https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

And especially the part with the 'git format patch' part.

2018-10-30 17:49 UTC, HaraldPanten approved these changes
Functionally is working fine :+1:

2018-11-09 15:40 UTC, ValentinVinagre commented
Hi @rousseldenis,
The commit history is correct?

2018-11-10 07:15 UTC, rousseldenis commented
@ValentinVinagre sounds good. But shouldn't two migration commits squashed into one?

2018-11-10 15:42 UTC, sbidoul requested changes
A few comments.

Also, it looks like your commits change the file permissions from 644 to 755 making them all executable. Can you fix that?

2018-11-10 15:42 UTC, sbidoul commented on stock_orderpoint_automatic_creation/readme/USAGE.rst
> +   :target: https://runbot.odoo-community.org/runbot/153/11.0
Do not put this image in USAGE.rst, it's now generated automatically as a readme badge.

2018-11-10 15:42 UTC, sbidoul commented on stock_orderpoint_automatic_creation/models/product_template.py
> +        string=_('Create Orderpoint'),
Do not add these `_`, it's done automatically by Odoo AFAIR

2018-12-31 06:51 UTC, rousseldenis commented
@ValentinVinagre

2019-04-27 11:13 UTC, rousseldenis commented
@ValentinVinagre Could you attend @sbidoul comments (it seems they are not resolved) and squash your commits ?

2019-09-30 11:42 UTC, rousseldenis commented
@ValentinVinagre

2020-03-20 21:14 UTC, closed without merging