[11.0][stock_available_unreserved][FIX] change computation method to check for unreserved quantity and avoid useless long compute method.
OCA/stock-logistics-warehouse pull request #511
Opened 2018-11-24 00:14 UTC by jbeficent

This fix implements a better mechanism to look for quants that have unreserved quantity.
The previous approach was unnecessarily defining a compute method in the quant that takes forever to compute during a migration from v10 to v11.

2018-11-24 12:14 UTC, rousseldenis requested changes
Code review. LGTM. 

@jbeficent Could you update module version ?

2018-11-26 07:07 UTC, aisopuro requested changes
Code review done.

I agree with @rousseldenis that this needs a version update. I would also like to see that the version be changed `11.0.1.0.0` -> `11.0.2.0.0`.

The rationale is that I think this is a breaking change: we introduce a new field and remove an old one. If anyone has built any modification on top of this module, we need to make it as clear as possible that they do not want to just blindly update to this newest version. As such, I feel we should increment the major version.

As a corollary I think the commit message should be tagged `[FEAT]` instead of `[FIX]`.

2018-11-26 07:07 UTC, aisopuro commented on stock_available_unreserved/models/product.py
> +        if value and operator == '>' and not (
Could you add a comment going through the reasoning why this is OK? I'll admit it seems to me that this isn't true: if you have a quant with `unreserved_quantity` 5 and a `quantity` of 10, and ask "which quants have `unreserved_quantity > 7`, this will say that the quant in question fits the criteria, despite not having the requested quantity.

I think the tests don't cover this situation, could you add a test (or a section to the existing test) to cover the scenario I described? Or just explain the obvious thing I missed that makes this clearly an Ok thing to do :laughing:

2018-11-26 07:07 UTC, aisopuro commented on stock_available_unreserved/views/stock_quant_view.xml
> -                        domain="[('contains_unreserved','=', True), ('location_id.usage','=', 'internal')]"/>
Would it be possible to re-engineer this filter to work with these new fields, instead of removing it entirely? Or is it agreed that this filter is useless?

2018-12-31 07:19 UTC, rousseldenis commented
@jbeficent

2019-02-07 16:52 UTC, bealdav commented on stock_available_unreserved/views/stock_quant_view.xml
> -                        domain="[('contains_unreserved','=', True), ('location_id.usage','=', 'internal')]"/>
Probably useless because you may specify which quantity you search for with advanced filter. It should not blocking, I think

2019-03-07 14:01 UTC, bealdav commented
@jbeficent could you have a look here please because #526 need it to be merged ?

Thanks a lot

2019-09-30 11:47 UTC, rousseldenis approved these changes

2021-05-29 07:24 UTC, rousseldenis commented
@JordiBForgeFlow Is this still applicable ?

2022-01-16 12:27 UTC, closed without merging