[11.0] [ADD] stock_request_analytic
OCA/stock-logistics-warehouse pull request #519
Opened 2018-12-24 16:25 UTC by AaronHForgeFlow

This means to integrate stock_request to analytics. The analytic account is passed from the stock_request to the stock moves. That way we can account for stock_requests and classify them.

### Roadmap
The integration with stock_request_purchase. Done in #520

2018-12-28 12:27 UTC, AaronHForgeFlow commented
This is ready to review. It seems there is some load issue in runbot, I'm restarting the build.

2018-12-31 07:28 UTC, rousseldenis requested changes
Code review

2018-12-31 07:28 UTC, rousseldenis commented on stock_request_analytic/models/stock_request_order.py
> +    analytic_count = fields.Integer(string='analytic count',
No need of the string

2018-12-31 07:28 UTC, rousseldenis commented on stock_request_analytic/models/stock_request_order.py
> +        readonly=True, copy=False)
IMHO copy is not needed

2018-12-31 07:28 UTC, rousseldenis commented on stock_request_analytic/models/stock_request_order.py
> +            req.analytic_ids = req.stock_request_ids.mapped(
I think this field does not exist

2019-01-03 16:52 UTC, lreficent commented
@rousseldenis I attended your review and dis some minor fixes. Could you have a look?

2019-01-09 10:11 UTC, LoisRForgeFlow approved these changes
IMO this is ready :+1:

2019-01-09 10:24 UTC, rousseldenis approved these changes
Code review. @aheficent Maybe you could use README fragments?

2019-01-09 10:26 UTC, merged