[packaging_uom] Add in README usage section
OCA/stock-logistics-warehouse pull request #521
Opened 2018-12-31 15:53 UTC by rafaelbn

Add the option to activate to be able to manage packaging in Odoo

cc @rousseldenis

2018-12-31 15:54 UTC, rafaelbn commented
![packaging_uom](https://user-images.githubusercontent.com/8736623/50563395-b34e2880-0d1c-11e9-9e80-6369d73bc298.png)

2019-03-27 18:17 UTC, rousseldenis commented on packaging_uom/README.rst
> + in the section Products -> Packaging Methods  -> the option "Manage available
Remove one space before '-> the option'

2019-03-27 18:18 UTC, rousseldenis requested changes
Minor comment. Thanks for completion !

Could you fix pylint too ?

2019-04-27 11:59 UTC, rousseldenis commented
@rafaelbn

2019-07-17 18:42 UTC, rafaelbn commented on packaging_uom/README.rst
> + in the section Products -> Packaging Methods  -> the option "Manage available
```suggestion
 in the section Products -> Packaging Methods -> the option "Manage available
```

2019-08-16 20:52 UTC, closed without merging

2019-08-16 20:52 UTC, rafaelbn commented
I opened https://github.com/OCA/stock-logistics-warehouse/pull/684