[ADD][10.0] stock_available_product_expiry - Add report
OCA/stock-logistics-warehouse pull request #530
Opened 2019-01-14 11:07 UTC by acsonefho

**Description**
Add a report to have details about stock scrap expired

**Technically**

- [x] Add the report

2019-01-14 11:32 UTC, rousseldenis requested changes
Code review. Some fixes

2019-01-14 11:32 UTC, rousseldenis commented on stock_available_product_expiry/reports/stock_scrap_expired.xml
> +                                    <th t-if="o.origin"><strong>Order (Origin)</strong></th>
@acsonefho IMHO, should be 'Source Document' See https://github.com/OCA/stock-logistics-warehouse/blob/10.0/stock_available_product_expiry/models/stock_scrap_expired.py#L31

2019-01-14 11:32 UTC, rousseldenis commented on stock_available_product_expiry/reports/stock_scrap_expired.xml
> +                            <t t-set="has_barcode" t-value="any([move.product_id and move.product_id.sudo().barcode for move in lines.mapped('move_id')])"/>
@acsonefho Everyone has product access. See https://github.com/odoo/odoo/blob/10.0/addons/product/security/ir.model.access.csv#L11

2019-01-14 11:32 UTC, rousseldenis commented on stock_available_product_expiry/reports/stock_scrap_expired.xml
> +                                            <img t-att-src="'/report/barcode/?type=%s&amp;value=%s&amp;width=%s&amp;height=%s' % ('Code128', line.product_id.barcode, 600, 100)" style="width:300px;hei
@acsonefho Should be EAN13. See https://github.com/odoo/odoo/blob/10.0/addons/product/report/product_product_templates.xml#L20

2019-01-14 13:53 UTC, acsonefho commented
@rousseldenis It should be ok now :)

2019-01-14 14:10 UTC, rousseldenis approved these changes

2019-01-15 15:33 UTC, Cedric-Pigeon approved these changes

2019-01-29 19:25 UTC, merged