[10.0] Fix mts+mto rules creation on warehouse creation
OCA/stock-logistics-warehouse pull request #555
Opened 2019-03-11 17:12 UTC by florian-dacosta

With the current version of the module, when you try to create a warehouse with the `mto_mts_management` flag, it fails.
Odoo raise an error here https://github.com/OCA/stock-logistics-warehouse/blob/10.0/stock_mts_mto_rule/model/warehouse.py#L35 because it did not yet write the data coming from `create_routes` mehod on the warehouse.
The same happens with mts_rules after.
I just move the logic from `create_routes` to `create` method in order to be sure the fields used in `_get_mts_mto_rule` are already filled.

2019-03-12 08:25 UTC, rousseldenis requested changes
Code review.

At least, change module version

2019-03-12 08:25 UTC, rousseldenis commented on stock_mts_mto_rule/model/warehouse.py
> +        if wh.mto_mts_management:
@florian-dacosta Maybe I would have put code here under into separate method (to easy override).

2019-03-12 08:34 UTC, hparfr approved these changes
+1 on minor version number.
This fix looks good to me.

2019-03-12 09:40 UTC, florian-dacosta commented
@rousseldenis 
I have attended your comments.
I thought the version change was done during the merge.

2019-03-12 10:15 UTC, rousseldenis commented
@florian-dacosta Nope, that depends on developer will.

Could you check Travis ?

2019-03-12 11:52 UTC, florian-dacosta commented
I fixed a test that was failing on stock_mts_mto_rule.
Unfortunatly, it seems there is still an error, but coming from another module I do not know.

2019-03-18 08:50 UTC, rousseldenis commented
@florian-dacosta Could you rebase ? 10.0 branch seems to be green, so...

2019-03-18 09:20 UTC, florian-dacosta commented
Strange indeed, I can't rebase as it is already up to date!

2019-03-18 09:37 UTC, rousseldenis commented
So, the error is due to this. In the log, they appear after installation of this module. Could you test those two modules with and without stock_mts_mto_rule one ?

2019-03-26 10:49 UTC, florian-dacosta commented
@rousseldenis 
I can't reproduce the problem, and I don't see how my fix could generate such an error.
The 10.0 branch seems red : https://travis-ci.org/OCA/stock-logistics-warehouse/builds/490502048
With the same problem, so it means the problem do not come from my PR, right?
Or am I missing something?

2019-03-26 10:53 UTC, rousseldenis commented
@florian-dacosta Yes, it seems that last good build is dated from 6th february on 10.0. I will explore log and keep you in touch

2019-03-26 10:57 UTC, rousseldenis commented
@florian-dacosta Ok. I know this. I found recently the solution on another repo.

Due to https://github.com/odoo/odoo/commit/2b1d3ff82dd23fb0372b3b73ecb84841a0d593d3 you have to raise ValidationError and not another exception in constrains.

I will propose a fix for this repo

2019-03-26 11:04 UTC, rousseldenis commented
https://github.com/OCA/stock-logistics-warehouse/pull/567

2019-03-26 12:51 UTC, rousseldenis commented
@florian-dacosta Green!

2019-03-26 12:52 UTC, florian-dacosta commented
Nice, thanks a lot @rousseldenis !

2019-03-26 14:30 UTC, rousseldenis approved these changes
Seems ok for me

2019-03-26 15:17 UTC, merged