[WIP][12.0] stock_request: Improved code based on v12.
OCA/stock-logistics-warehouse pull request #556
Opened 2019-03-13 15:31 UTC by murtuzasaleh

**WIP**

2019-03-14 10:35 UTC, rousseldenis commented
@murtuzasaleh Thanks for your contribution. Could you maybe change your PR title to be a little bit clearer? If it is a migration to 12, you can say [12.0][MIG] stock_request

2019-03-14 10:39 UTC, murtuzasaleh commented
> @murtuzasaleh Thanks for your contribution. Could you maybe change your PR title to be a little bit clearer? If it is a migration to 12, you can say [12.0][MIG] stock_request

Sure I will do it, now It is WIP.

2019-03-20 11:34 UTC, nikul-serpentcs commented
@pedrobaeza Can you please check why Runbot is Rad/False?

2019-03-20 18:17 UTC, pedrobaeza commented
```
2019-03-20 11:28:06,596 161 WARNING openerp_test odoo.addons.base.models.ir_model: Two fields (route_ids, route_id) of stock.request.abstract() have the same label: Route.
2019-03-20 11:28:06,609 161 WARNING openerp_test odoo.addons.base.models.ir_model: Two fields (route_ids, route_id) of stock.request() have the same label: Route.
```

2019-03-22 14:51 UTC, murtuzasaleh commented
@jbeficent @hveficent Can you please review this PR.

2019-03-22 15:33 UTC, HviorForgeFlow requested changes
cherry-pick my commit 2753108d1cead447440cc6258d1570febcb7a1d7 and rebase.

2019-03-25 05:49 UTC, murtuzasaleh commented
> cherry-pick my commit [2753108](https://github.com/OCA/stock-logistics-warehouse/commit/2753108d1cead447440cc6258d1570febcb7a1d7) and rebase.

I have added that commit [2753108](https://github.com/OCA/stock-logistics-warehouse/commit/2753108d1cead447440cc6258d1570febcb7a1d7) in my PR when your PR is not merged, Can I revert my code and cherry-pick your commit and rebase it?

2019-03-27 10:09 UTC, HviorForgeFlow requested changes
:man_firefighter:

2019-03-27 10:09 UTC, hveficent commented on stock_request/security/stock_request_security.xml
> +        <field name="users" eval="[(4, ref('base.user_root'))]"/>
Functional review (first attempt):
I'm only able to access to Stock Request General Settings if I use Become a SuperUser, i think problem is that now admin user is defined as base.user_admin

2019-04-10 15:14 UTC, max3903 commented
@osi-scampbell Please test, review and comment. Thanks!

2019-04-12 17:54 UTC, osi-scampbell approved these changes
Code installs cleanly and everything appears to be working on my end. @murtuzasaleh can you squash you last few commits please?

2019-04-15 14:17 UTC, max3903 approved these changes

2019-04-15 19:30 UTC, merged