Add stock _inventory_import (migrated from odoomrp-wip)
OCA/stock-logistics-warehouse pull request #56
Opened 2015-06-05 16:25 UTC by tafaRU

This PR contains the module 'stock_inventory_import' migrated from https://github.com/odoomrp/odoomrp-wip according to https://github.com/odoomrp/odoomrp-wip/wiki/Migration-to-OCA

2015-06-07 22:59 UTC, pedrobaeza commented on stock_inventory_import/README.rst
> +The file must have at least 2 columns with "code" and "quantity" Head Keys.
This can be in the "Configuration" section.

2015-06-07 23:00 UTC, pedrobaeza commented on stock_inventory_import/models/__init__.py
> +
Put encoding

2015-06-07 23:00 UTC, pedrobaeza commented on stock_inventory_import/models/stock_inventory.py
> +#
Put encoding

2015-06-07 23:00 UTC, pedrobaeza commented on stock_inventory_import/security/.directory
> +[Dolphin]
Remove this file

2015-06-07 23:01 UTC, pedrobaeza commented on stock_inventory_import/security/ir.model.access.csv
> +access_stock_inventory_import_line,access_stock_inventory_import_line,model_stock_inventory_import_line,stock.group_stock_manager,1,1,1,1
Put also read access to warehouse user, as inventory has.

2015-06-07 23:01 UTC, pedrobaeza commented on stock_inventory_import/wizard/__init__.py
> +
Put encoding

2015-06-07 23:01 UTC, pedrobaeza commented on stock_inventory_import/wizard/import_inventory.py
> +
Put encoding

2015-06-07 23:02 UTC, pedrobaeza commented on stock_inventory_import/wizard/import_inventory.py
> +        return inventory.location_id
Indent this line one level more and add another one `return False` as fallback.

2015-06-07 23:02 UTC, pedrobaeza commented on stock_inventory_import/wizard/import_inventory_view.xml
> +<!--     <menuitem  id="menu_import_inventory" name="Import Inventory" action="action_import_inventory" parent="stock.menu_stock_inventory_control"/> -->
Remove this commented section

2015-06-15 10:33 UTC, tafaRU commented
@pedrobaeza I think all your remarks have been addressed, could you please check it?
Thank you in advance.

2015-06-27 11:43 UTC, pedrobaeza commented
:+1:

2015-07-16 10:05 UTC, eLBati commented on stock_inventory_import/README.rst
> +`here <https://github.com/OCA/{stock-logistics-workflow}/issues/new?body=module:%20{stock_inventory_import}%0Aversion:%20{version}%0A%0A**Steps%20to%20reproduce**%0A-%20...%0A%0A**Current%20behavior*
please remove ```{``` ```}```

2015-07-16 10:55 UTC, tafaRU commented on stock_inventory_import/README.rst
> +`here <https://github.com/OCA/{stock-logistics-workflow}/issues/new?body=module:%20{stock_inventory_import}%0Aversion:%20{version}%0A%0A**Steps%20to%20reproduce**%0A-%20...%0A%0A**Current%20behavior*
@eLBati, done.

2015-07-17 06:51 UTC, eLBati commented
:+1: thanks

2015-07-30 19:20 UTC, pedrobaeza commented
Can you add tests for exercising this module?

2016-03-21 14:41 UTC, gurneyalex commented
@tafaRU could you rebase the PR please?

2016-03-21 14:55 UTC, tafaRU commented
> @tafaRU could you rebase the PR please?

@gurneyalex, done

2016-08-09 14:09 UTC, eLBati commented on stock_inventory_import/__openerp__.py
> +    "version": "1.0",
Please use 8.0.1.0.0

2016-08-09 14:11 UTC, eLBati commented
@tafaRU could you rebase to see if tests errors related to ```stock_available_mrp``` are fixed?

2016-08-24 09:08 UTC, pedrobaeza commented
There's a new commit solving a little issue in odoomrp-wip. Please cherry-pick.

2016-10-06 09:05 UTC, tafaRU commented on stock_inventory_import/__openerp__.py
> +    "version": "1.0",
@eLBati, done at https://github.com/OCA/stock-logistics-warehouse/pull/56/commits/b2ef44224a3c1b8c52b90d9fa0fdf24a87d6dc27

2016-10-06 09:07 UTC, tafaRU commented
@pedrobaeza, cherry-pick done, please see https://github.com/OCA/stock-logistics-warehouse/pull/56/commits/f210de422dab47633d34949707166414948b000a

2016-10-06 10:12 UTC, andhit-r requested changes
Functionality: Ok (tested on runbot)

Code:
1. Travis is still failed
2. Misused @api.one insted @api.multi
3. Minor details

2016-10-06 10:12 UTC, andhit-r commented on stock_inventory_import/README.rst
> +Bugs are tracked on `GitHub Issues <https://github.com/OCA/stock-logistics-warehouse/issues>`_.
Use new format, see https://github.com/OCA/maintainer-tools/blame/master/template/module/README.rst#L52

2016-10-06 10:12 UTC, andhit-r commented on stock_inventory_import/README.rst
> +To contribute to this module, please visit http://odoo-community.org.
https

2016-10-06 10:12 UTC, andhit-r commented on stock_inventory_import/__init__.py
> +##############################################################################
Use simple header

2016-10-06 10:12 UTC, andhit-r commented on stock_inventory_import/__openerp__.py
> +##############################################################################
Use simple header

2016-10-06 10:12 UTC, andhit-r commented on stock_inventory_import/__openerp__.py
> +    "contributors": [
no need, already on README

2016-10-06 10:12 UTC, andhit-r commented on stock_inventory_import/models/__init__.py
> +##############################################################################
Use simple header

2016-10-06 10:12 UTC, andhit-r commented on stock_inventory_import/models/stock_inventory.py
> +##############################################################################
Use simple header

2016-10-06 10:12 UTC, andhit-r commented on stock_inventory_import/wizard/__init__.py
> +##############################################################################
Use simple header

2016-10-06 10:12 UTC, andhit-r commented on stock_inventory_import/wizard/import_inventory.py
> +##############################################################################
Use simple header

2016-10-06 10:12 UTC, andhit-r commented on stock_inventory_import/wizard/import_inventory.py
> +    @api.one
Use @api.multi with self.ensure_one()

2016-10-06 10:12 UTC, andhit-r commented on stock_inventory_import/wizard/import_inventory.py
> +from openerp import fields, models, exceptions, api, _
Use:
```
from openerp.exceptions import Warning as UserError 
``` 
as stated on https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#idioms

2016-10-06 10:56 UTC, tafaRU commented
@pedrobaeza, a couple of questions:

- which author can I use into the header?
- OCA needs to be added as author in the manifest file?

Thank you in avance.

2016-10-10 09:34 UTC, pedrobaeza commented
You can add `Tecnativa` and `AvanzOSC` as original authors.

You should add OCA also as co-author.

2016-10-10 12:51 UTC, tafaRU commented
@andhit-r, I addressed your remarks, please have a look at it.

2016-10-12 07:22 UTC, andhit-r approved these changes
:+1:

2016-10-12 07:41 UTC, tafaRU commented
PR is ready to be merged! Could someone of @OCA/logistics-maintainers please do it?
Thank you in advance.

2016-10-12 08:07 UTC, pedrobaeza approved these changes
Merging and amending some details after (author, module category and license link)

2016-10-12 08:09 UTC, pedrobaeza requested changes
Hey, wait a moment, Travis status is red. Please check that. You can also amend the rest of the commented things

2016-10-12 08:09 UTC, pedrobaeza commented on stock_inventory_import/README.rst
> +    :alt: License: AGPL-3
Add license link

2016-10-12 08:09 UTC, pedrobaeza commented on stock_inventory_import/__openerp__.py
> +    "category": "Generic Modules",
Change this to "Warehouse Management"

2016-10-12 08:09 UTC, pedrobaeza commented on stock_inventory_import/__openerp__.py
> +              "Serv. Tecnol. Avanzados - Pedro M. Baeza, "
Change this to `Tecnativa`

2016-10-12 15:09 UTC, tafaRU commented
@pedrobaeza, I fixed the things you commented.
Travis is still red but I don't think it's related to this module especially because it doensn't contain any tests.

2016-10-12 23:17 UTC, pedrobaeza commented
Please rebase on latest 8.0 branch to see

2016-10-13 07:38 UTC, tafaRU commented
@pedrobaeza, rebased but travis is still red :expressionless:

2016-10-13 14:39 UTC, tafaRU commented
Travis will be green once https://github.com/OCA/stock-logistics-warehouse/pull/140 will be merged.

2016-10-13 15:25 UTC, jbeficent commented
@tafaRU I have now merged https://github.com/OCA/stock-logistics-warehouse/pull/140 and restarted Travis for this PR.

2016-10-13 15:30 UTC, tafaRU commented
Thanks @jbeficent, I've just rebased, let's see!

2016-10-25 13:20 UTC, eLBati commented
still red

2017-05-29 14:47 UTC, Cedric-Pigeon commented
@tafaRU Hello, do you plan to achieve this PR ? Is it still usefull ? thanks

2018-05-04 00:23 UTC, pedrobaeza commented
No answer, so I close it. Feel free to reopen if needed.

2018-05-04 00:23 UTC, closed without merging