MIG stock_mts_mto_rule to 12.0
OCA/stock-logistics-warehouse pull request #586
Opened 2019-05-06 15:34 UTC by jaredkipe

There were major changes to the way Warehouses maintain their routes/rules and self heal in 12.0 

This necessitated large changes to `models/stock_warehouse.py` and some changes to test expectations.

In general, I read through the new Odoo code to get a feel for how they are updating and healing routes, then I applied the same methodology to the refactor work. I didn't really comment these methods as a search through **purchase, mrp, stock** for the same method names will turn up very similar looking code (that is also not commented).

Some not so great things...
In the model `stock.warehouse` Odoo provides a shim for an old method named `get_all_routes_for_wh` that is now effectively named `_get_all_routes`.  However, in **purchase_stock** module, they incorrectly call the parent method that isn't actually the method being called.

```
    @api.multi
    def _get_all_routes(self):
        routes = super(StockWarehouse, self).get_all_routes_for_wh()
```

This can lead to infinite loops, so ultimately I ended up just resorting to the same 'shim' approach that Odoo took.

2019-05-13 23:28 UTC, manney commented
We've just pulled this branch.  I did a quick functional test on it as well as ran all of the tests.  Everything seems to pass with flying colors.  :+1:

2019-05-14 00:34 UTC, jaredkipe commented
@manney thank you!

Anyone else interested in trying it, and potentially other beta branches like `connector` is welcome to use our automated docker builds at `registry.gitlab.com/hibou-io/hibou-odoo/suite:12.0-test`

2019-05-14 09:41 UTC, rousseldenis requested changes
Code review.

2019-05-14 09:41 UTC, rousseldenis commented on stock_mts_mto_rule/__init__.py
> +from . import model
models
https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#directories

2019-05-14 09:41 UTC, rousseldenis commented on stock_mts_mto_rule/__manifest__.py
> + 'website': 'http://www.akretion.com',
Could you follow OCA conventions for manifest (website, missing entires) ?

https://github.com/OCA/maintainer-tools/blob/master/template/module/__manifest__.py

2019-05-14 09:41 UTC, rousseldenis commented on stock_mts_mto_rule/__manifest__.py
> + 'demo': [],
Please remove void one

2019-05-14 09:41 UTC, rousseldenis commented on stock_mts_mto_rule/model/stock_rule.py
> +                    raise UserError(msg)
Constrains must raise ValidationError

2019-05-14 09:41 UTC, rousseldenis commented on stock_mts_mto_rule/model/stock_rule.py
> +                    raise UserError(msg)
Constrains must raise ValidationError

2019-05-14 09:41 UTC, rousseldenis commented on stock_mts_mto_rule/model/stock_rule.py
> +        if qty_available > 0:
You should use float_compare

2019-05-14 09:41 UTC, rousseldenis commented on stock_mts_mto_rule/model/stock_rule.py
> +        if needed_qty == 0.0:
You should use float_is_zero

2019-05-14 09:41 UTC, rousseldenis commented on stock_mts_mto_rule/model/stock_rule.py
> +        elif needed_qty == product_qty:
You should use float_compare

2019-05-14 09:41 UTC, rousseldenis commented on stock_mts_mto_rule/model/stock_warehouse.py
> +from odoo import models, fields
```suggestion
from odoo import fields, models, _
```

2019-05-14 13:37 UTC, florian-dacosta requested changes
Thanks for the migration!
I made some minor comments
Otherwise I did functional tests and it seems to work as expected.

2019-05-14 13:37 UTC, florian-dacosta commented on stock_mts_mto_rule/README.rst
> +.. image:: https://img.shields.io/badge/license-AGPL--3-blue.png
It would be nice to split the readme, like explain here : https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0

2019-05-14 13:37 UTC, florian-dacosta commented on stock_mts_mto_rule/README.rst
> +
You can add yourself in the contributor list, but not in the authors

2019-05-14 13:37 UTC, florian-dacosta commented on stock_mts_mto_rule/__manifest__.py
> + 'author': 'Hibou Corp.,Akretion,Odoo Community Association (OCA)',
You should put yourself in the contributor and not in the authors

2019-05-27 07:29 UTC, rousseldenis commented
@jaredkipe Do you plan to attend comments?

2019-05-27 20:38 UTC, jacekdalecki84 commented
nothing specific. at this moment he will give a git chada and honestly say little wien.

2019-05-28 09:37 UTC, rousseldenis commented
> nothing specific. at this moment he will give a git chada and honestly say little wien.

Ugh, didn't understand...

2019-06-04 18:03 UTC, jaredkipe commented
Now that Odoo has merged in https://github.com/odoo/odoo/pull/33288 , I have removed the patch and re-worked the test.

Otherwise I believe I have addressed everyone's concerns other than splitting the README into multiple files.

2019-06-04 19:03 UTC, rousseldenis commented
@jaredkipe Just lint errors and LGTM!

2019-06-06 00:09 UTC, jaredkipe commented
Should be good now, feel free to squash as there are now a couple of simple 'fix' commits that don't really help.

2019-06-06 08:19 UTC, florian-dacosta approved these changes

2019-06-06 08:21 UTC, rousseldenis commented
> Should be good now, feel free to squash as there are now a couple of simple 'fix' commits that don't really help.

Hi Jared, I cannot just squash your four migration commits during merging. Could you do it ?

2019-06-06 19:23 UTC, jaredkipe commented
All done with that, the only major difference is that it now thinks the `stock_warehouse.py` file is a complete rewrite due to the changes and `model` => `models` module rename.

2019-06-21 08:41 UTC, salbassersyentys commented
Hi Folks, any idea when this PR is likely to be approved? we do have a customer waiting on this - blocking issue for him & his business. Would be very much appreciated, thanks a lot in advance! :-)

2019-06-21 08:43 UTC, rousseldenis approved these changes
Code review. LGTM

2019-06-21 09:01 UTC, rousseldenis commented
/ocabot merge

2019-06-21 10:00 UTC, closed without merging