[12.0][MIG] stock_available: Migration to v12.0
OCA/stock-logistics-warehouse pull request #632
Opened 2019-06-26 18:44 UTC by sergio-teruel

cc @Tecnativa

2019-06-26 18:57 UTC, pedrobaeza commented on stock_available/README.rst
> +* `Sodexis <https://www.Sodexis.com>`_:
You must leave an empty line for proper RST syntax

2019-06-26 18:57 UTC, pedrobaeza commented on stock_available/views/product_product_view.xml
> +                            <span class="o_stat_value" widget="statinfo">
Good change mimicking the style of v12 stock on hand and company smart-buttons!

2019-06-26 19:09 UTC, sergio-teruel commented
@pedrobaeza Changes done!!

2019-06-26 19:25 UTC, pedrobaeza approved these changes

2019-06-26 19:30 UTC, pedrobaeza commented
@sergio-teruel I'm seeing that this module is already migrated in #540, so we have a conflict. Please always check first before migrating a module if there's another one. The other one seems to have an interesting change from 10.0, and yours have about the style on the smart-buttons. I'm going to ask in the other PR if they are interested in continuing it.

2019-06-27 15:11 UTC, pedrobaeza commented
@sergio-teruel please include missing v10 commits that are on the other PR. Or they are here already?

2019-06-27 15:29 UTC, sergio-teruel commented
@pedrobaeza Yes, they were already included.

2019-06-27 15:32 UTC, pedrobaeza commented
OK, great

2019-06-27 15:32 UTC, pedrobaeza approved these changes

2019-06-27 16:13 UTC, victor-ditay approved these changes

2019-06-28 15:37 UTC, Tardo requested changes

2019-06-28 15:37 UTC, Tardo commented on stock_available/models/product_template.py
> +OPERATORS = {
This is used more than once... perhaps can be good export it to a separated .py ? for example "utils.py"

2019-07-02 08:57 UTC, sergio-teruel commented
@Tardo Changes done!!

2019-07-02 09:06 UTC, rousseldenis requested changes
Code review. Just a change

2019-07-02 09:06 UTC, rousseldenis commented on stock_available/models/product_template.py
> +OPERATORS = {
I would have said that it is included in Odoo, so:

```suggestion
from odoo.addons.stock.models.product import OPERATORS
```

2019-07-02 09:06 UTC, rousseldenis commented on stock_available/models/product_product.py
> +from .product_template import OPERATORS
from odoo.addons.stock.models.product import OPERATORS

2019-07-02 20:46 UTC, sergio-teruel commented on stock_available/models/product_product.py
> +from .product_template import OPERATORS
thanks @rousseldenis

2019-07-03 07:32 UTC, pedrobaeza commented
Please check Travis and runbot status

2019-07-04 09:38 UTC, sergio-teruel commented
Travis Ok

2019-07-04 09:41 UTC, rousseldenis approved these changes
Code review. Could you squash ?

2019-07-04 10:19 UTC, florian-dacosta approved these changes
Tests + code review

2019-07-04 10:28 UTC, pedrobaeza commented
@sergio-teruel next time you edit from the GitHub interface, what you can do is to change commit message to comply with "!fixup <previous commit name>", and this way, OCA Bot will auto-squash it. Are you squashing now?

2019-07-05 10:03 UTC, Tardo approved these changes

2019-07-05 10:33 UTC, pedrobaeza commented
/ocabot merge

2019-07-05 12:11 UTC, merged