[12.0][MIG] stock_account_inventory_force_date
OCA/stock-logistics-warehouse pull request #676
Opened 2019-08-02 08:58 UTC by hveficent

Standard migration

CC @Eficent

2019-08-02 15:22 UTC, daramousk requested changes

2019-08-02 15:22 UTC, daramousk commented on stock_account_inventory_force_date/models/stock_inventory.py
> +            self.accounting_date = self.date
This results in a crash since `accounting_date` is `Date` while `date` is `Datetime` (unfortunate naming), calling tostring on `self.date` should suffice.

2019-08-05 09:26 UTC, hveficent commented on stock_account_inventory_force_date/models/stock_inventory.py
> +            self.accounting_date = self.date
You are right. New changes proposed.

2019-09-30 12:12 UTC, rousseldenis approved these changes
Code review

2019-10-07 07:48 UTC, hveficent commented
@daramousk can you update your review? Thanks!

2019-10-15 09:38 UTC, hveficent commented
ping @daramousk

2019-10-15 09:41 UTC, daramousk approved these changes
Looks great, although the code coverage needs to be raised so that stuff gets green.

2019-10-15 20:41 UTC, rousseldenis commented
@hveficent Do you plan to increase coverage ?

2019-10-16 08:33 UTC, hveficent commented
@rousseldenis @daramousk, I think current tests cover most of the use cases. Not full coverage is due to doing an Inventory Adjustment of all product, so I can make it happen, but asserts can't be precise across changes in demo data, so I think it is not needed and it is ready to be merged.

2019-10-16 14:46 UTC, rousseldenis commented
/ocabot merge

2019-10-16 18:40 UTC, merged