12.0 rework stock location zone
OCA/stock-logistics-warehouse pull request #711
Opened 2019-09-11 10:09 UTC by grindtildeath

Followup to #653

2019-09-11 13:02 UTC, grindtildeath commented on stock_location_zone/models/stock_location.py
> +        'unique(name, zone_location_id)',
Add `company_id`

2019-09-11 13:10 UTC, grindtildeath commented on stock_location_zone/models/stock_location.py
>      def _compute_area(self):
To move to #713

2019-09-11 15:37 UTC, rousseldenis commented
How fast reaction :smile: :+1:

2019-09-17 11:26 UTC, daramousk requested changes

2019-09-17 11:26 UTC, daramousk commented on stock_location_zone/models/stock_location.py
> +    )
This could be `store=True` as well, mostly because you cannot group them otherwise.

2019-09-17 11:26 UTC, daramousk commented on stock_location_zone/views/stock_location.xml
> +                    <filter string="Location Kind" name="location_kind" domain="[]" context="{'group_by':'location_kind'}"/>
This cannot work since the field is not persisted.

2019-09-17 11:26 UTC, daramousk commented on stock_location_zone/models/stock_location.py
> +                zone_location = self.browse()
Unessesary if you `zone_location = self` in the beginning.

2019-09-20 13:28 UTC, guewen commented on stock_location_zone/models/stock_location.py
> +    )
Added

2019-09-20 13:30 UTC, guewen commented
Reworked the function fields, added `store=True` and added an `area_location_id` similar to `zone_location_id`.

2019-11-12 11:18 UTC, jbaudoux commented on stock_location_zone/readme/DESCRIPTION.rst
> +* Zone: locations that are flagged as being zones
```suggestion
* Zone: locations that are flagged as being zones. Zones are subdivisions of the warehouse for splitting picking operations. A picking operator work in a zone and can pick from any location of the zone.
```

2019-11-12 11:20 UTC, jbaudoux commented on stock_location_zone/readme/DESCRIPTION.rst
> +* Area: locations with children that are part of a zone
```suggestion
* Area: locations with children that are part of a zone. Areas are subdivisions of the warehouse for put-away operations. Each area has storage characteristics and strategy, e.g. area for pallets, shelf for boxes...
```

2020-09-29 14:17 UTC, jgrandguillaume commented
/ocabot merge nobump

2021-05-29 07:39 UTC, rousseldenis commented
/ocabot merge nobump

2021-11-12 11:48 UTC, rousseldenis commented
/ocabot merge nobump

2021-11-12 12:53 UTC, merged