[ADD] Add stock_reminder
OCA/stock-logistics-warehouse pull request #721
Opened 2019-09-20 16:22 UTC by daramousk

2019-10-01 08:32 UTC, rousseldenis commented
@daramousk I've restarted travis job as a fix has been merged.

2019-10-01 09:05 UTC, rousseldenis commented
@daramousk Could you rebase?

2019-10-15 21:01 UTC, rousseldenis requested changes
Code review. Some required changes.

The worse point I see here, if there are some products that trigger often the reminder, the chatter on the product form could be bulky to manage.

2019-10-15 21:01 UTC, rousseldenis commented on stock_reminder/models/stock_reminder.py
> +        required=True
ondelete='cascade' ?

2019-10-15 21:01 UTC, rousseldenis commented on stock_reminder/models/stock_reminder.py
> +        required=True,
ondelete='cascade' ?

2019-10-15 21:01 UTC, rousseldenis commented on stock_reminder/models/stock_reminder.py
> +            if self.env.user.has_group('stock.group_stock_user'):
Put this before the loop.

2019-10-15 21:01 UTC, rousseldenis commented on stock_reminder/models/stock_reminder.py
> +            model_product_product.browse(product_id).message_subscribe_users(
Why re-browsing product ?

2019-10-15 21:01 UTC, rousseldenis commented on stock_reminder/models/stock_reminder.py
> +            result = safe_eval(
You cannot do that in that way. You need to use float_compare method.

2019-10-15 21:01 UTC, rousseldenis commented on stock_reminder/models/stock_reminder.py
> +        self.env['product.product'].browse(
Why not using 'message_subscribe' as here under ?

2020-10-09 11:41 UTC, rousseldenis commented
@daramousk Do you plan to attend comments ?

2020-10-09 11:42 UTC, daramousk commented
@rousseldenis i will, if not today tomorrow

2021-05-29 07:45 UTC, rousseldenis commented
@daramousk We are almost tomorrow :sweat_smile:

2022-03-20 12:26 UTC, closed without merging