[8.0][FIX] .travis: Update to latest template
OCA/stock-logistics-warehouse pull request #730
Opened 2019-09-30 12:46 UTC by rousseldenis

2019-09-30 20:40 UTC, pedrobaeza requested changes

2019-09-30 20:40 UTC, pedrobaeza commented on .travis.yml
> +  - WEBSITE_REPO="1"
No need to install all of this stuff

2019-10-01 08:21 UTC, rousseldenis commented on .travis.yml
> +  - WEBSITE_REPO="1"
Is it ok now?

2019-10-01 08:29 UTC, pedrobaeza approved these changes

2019-10-01 08:29 UTC, merged