[12.0][ADD] stock_location_empty
OCA/stock-logistics-warehouse pull request #766
Opened 2019-11-22 08:19 UTC by TDu

2019-11-22 08:35 UTC, i-vyshnevska commented on stock_location_empty/models/stock_location.py
> +            HAVING coalesce(sum(quantity), 0) %s %%s;"""
```suggestion
            HAVING coalesce(sum(quantity), 0) %s %%s;"""
```
is it correct?

2019-11-22 08:54 UTC, i-vyshnevska approved these changes

2019-11-25 21:39 UTC, rousseldenis requested changes
Code review.

2019-11-25 21:39 UTC, rousseldenis commented on stock_location_empty/__manifest__.py
> +{'name': 'Stock Location Empty',
Can you update this according to https://github.com/OCA/maintainer-tools/blob/master/template/module/__manifest__.py ?

2019-11-25 21:39 UTC, rousseldenis commented on stock_location_empty/__manifest__.py
> + 'category': 'stock',
Change this to 'Warehouse' as it won't appear in the good category in OCA shop

2019-11-25 21:39 UTC, rousseldenis commented on stock_location_empty/models/stock_location.py
> +    stock_amount = fields.Integer(
I'd prefer stock_quantity as amount is more related to monetary.
Moreover, this field should be Float

2019-11-25 21:39 UTC, rousseldenis commented on stock_location_empty/models/stock_location.py
> +        # pylint: disable=sql-injection
Don't do that. Pylint error says that you have to pass parameters to second argument:

`cr.execute("blabla %s", value)`

2019-11-25 21:39 UTC, rousseldenis commented on stock_location_empty/models/stock_location.py
> +        self.env.cr.execute(
Why not using read_group ???

2019-11-25 21:39 UTC, rousseldenis commented on stock_location_empty/models/stock_location.py
> +        self.env.cr.execute(
Same as above, use read_group

2021-05-18 14:46 UTC, yvaucher commented
@TDu ping

2022-05-01 12:30 UTC, closed without merging