[13.0][MIG] stock_available_mrp
OCA/stock-logistics-warehouse pull request #803
Opened 2019-12-19 08:42 UTC by ps-tubtim

2020-06-15 12:23 UTC, m-abdalrahman commented
hello @ps-tubtim I can't enter the products screen after installing the module
![Screenshot from 2020-06-15 14-18-38](https://user-images.githubusercontent.com/19738046/84656705-66134600-af13-11ea-8cbd-a19fd7bacd12.png)

log:
`odoo.http: ('product.product(1,).bom_id', None)
`

2020-08-24 12:43 UTC, rousseldenis commented
@ps-tubtim You can rebase as #802 is merged

2021-01-16 10:21 UTC, i-vyshnevska commented
@ ps-tubtim can you pls rebase and check travis build for errors

2021-02-02 19:30 UTC, leemannd commented
Hello @ps-tubtim I created a PR to fix your migration. It could be great if you can merge it https://github.com/ecosoft-odoo/stock-logistics-warehouse/pull/2

2021-02-03 08:04 UTC, leemannd reviewed
Missing returb

2021-02-03 08:04 UTC, leemannd commented on stock_available_mrp/models/product_product.py
> +                product.bom_id = first(product_boms)
```suggestion
                product.bom_id = first(product_boms)
            else:
                product.bom_id = False
```

2021-02-03 08:05 UTC, leemannd requested changes
Missing return in compute function. This will lead to the impossibility to see products

2021-02-26 08:43 UTC, chienandalu commented
We just merged this changes due to Odoo upstream changes that intruduced some incompatibilities. https://github.com/OCA/stock-logistics-warehouse/pull/1099/files Please include it in your migration

2021-03-04 08:20 UTC, ps-tubtim commented on stock_available_mrp/models/product_product.py
> +                product.bom_id = first(product_boms)
Thank you for your review. Edited.

2021-06-29 11:24 UTC, leemannd commented
This can be closed. The module has been migrated into another PR

2021-07-29 04:51 UTC, closed without merging