[13.0][MIG] stock_request
OCA/stock-logistics-warehouse pull request #839
Opened 2020-01-29 12:59 UTC by HviorForgeFlow

Standard migration

CC @Forgeflow @etobella

2020-01-29 15:28 UTC, AdriaGForgeFlow commented on stock_request/__manifest__.py
> +    "author": "Eficent, Odoo Community Association (OCA)",
Could you change this to ForgeFlow?

2020-01-30 16:10 UTC, AdriaGForgeFlow requested changes
Quantities are not correctly updated in the Stock Request

2020-02-05 10:38 UTC, HviorForgeFlow commented
> Quantities are not correctly updated in the Stock Request

It works on runbot for me. Can you check to reproduce it there? Thanks,

2020-03-10 12:43 UTC, JoanSForgeFlow approved these changes
Functional review, LGTM :+1:

2020-03-12 03:08 UTC, ps-tubtim approved these changes
Code LGTM. Functional test: OK.

2020-03-12 12:49 UTC, LoisRForgeFlow commented
@AdriaGForgeFlow Your comments will be fixed with stock_request_purchase.

Ready to merge: 

/ocabot merge

2020-03-12 13:21 UTC, merged