[13.0] Add module stock_move_common_dest_sync_location - alpha
OCA/stock-logistics-warehouse pull request #862
Opened 2020-03-11 10:43 UTC by grindtildeath

Depends on: 
 - [ ] #861

2020-03-11 10:52 UTC, guewen commented on stock_move_common_dest_sync_location/models/stock_move_line.py
> +                if not self.picking_type_sync_common_move_dest_location:
```suggestion
                if not move_line.picking_type_sync_common_move_dest_location:
```

2020-05-04 06:07 UTC, jgrandguillaume approved these changes
LGTM, though it'll need more extensive testing to see how it behave. I would be in favor of merging this as alpha because it works as expected. We just don't know now if the feature will be relevant in all context.

2020-05-14 07:14 UTC, guewen requested changes
We shouldn't merge it. I'll soon propose a new solution to solve the issue.
I'll close this PR when I open the new one.

2020-05-19 11:30 UTC, guewen commented
The replacement for this feature is #907

2020-05-19 11:30 UTC, closed without merging